### ISSUE TITLE
Fix empty error message with non-row specific errors during bulk validation

### ISSUE THREAD

**Issue by DerekFurstPitt** [hubmapconsortium/ingest-ui#1012]
When an error in validation occurs when registering a bulk tsv file that is not specific to a given row (such as a bad field in the header or mismatched header/row columns) rather than showing the error message, the field is blank. 

![image](https://user-images.githubusercontent.com/85903206/210425615-5185ea7a-70d0-4db5-a81e-bb52e170489e.png)

This is likely due to the difference between json's returned during a row specific error from ingest-api and a non-specific row error. 

@BirdMachine I am uncertain exactly how the ingest-ui typically parses that incoming json. But if there were an error, for example with a source_id being invalid for a given row, the json would look like this: 

```
{
    "data": {
        "0": "Row Number: 1. <source_id> is not a valid id format"
    },
    "status": "fail"
}
```

Where 0 is the error number and row is the row number (there can be multiple errors per row) 

However if there is an extra row in the header column (which the csv library interprets as an empty string in a list) the returned json looks like this:

```
{
    "data": {
        "0": "<blank> is not an accepted field"
    },
    "status": "fail"
}
```
where again 0 is the error number, but here there is no row number. I suspect this is why the error popup has no message field. Somewhere along the way the parsing gets messed up because its expecting a row number. 

When one of these non-row-specific validation errors occur, the actual rows beneath the header aren't even validated. 

While its likely the fix will be in the UI, I can make changes to the output of the json to behave more predictably if you think it would help. Perhaps if one of these non-row errors is thrown, I can still report a -1 as the row or something. however you think best to format these so the ui can process them, I'll make the output json that way.

**Comment by BirdMachine** [comment]
Merged in pr #1020
