### ISSUE TITLE
Link to Datasets from Uploads screen incorrect

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/ingest-ui#1015]
The link from "Reorganized" Datasets on an Upload page are broken, they go to `/datasets/<id>` instead of the correct `/dataset/<id>` (URL has singular dataset vs plural datasets)  for example on Upload 
https://ingest.hubmapconsortium.org/upload/81ab1f8ff2cb528f249b7fa6d81c58a2

https://ingest.hubmapconsortium.org/datasets/f852d653926edb68292e39b95a3469cf
doesn't work, but editing the url by hand to
https://ingest.hubmapconsortium.org/dataset/f852d653926edb68292e39b95a3469cf
does work.

**Comment by BirdMachine** [comment]
Merged in #1016
