### ISSUE TITLE
Add `Paper` form

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/ingest-ui#1048]
Add a new form to create/edit the new entity `Paper`defined in the entity-api [Add Paper Entity issue](https://github.com/hubmapconsortium/entity-api/issues/439)
  - create form accessed via a `Paper` item in the "Individual" dropdown menu
  - add top level `Paper` entry to the search page Type dropdown to search for only papers
  - Collect the Source(s)/ancesters of the paper with the same multi-select source control used for `Datasets`
  - Collect the field Abstract and store in the `description` field
  - Collect all of the fields listed in the [Add Paper Entity issue](https://github.com/hubmapconsortium/entity-api/issues/439)
  - on create save/POST set `data_types` to `["Publication"]`
  - on create save/POST set `contains_human_genetic_sequences` to False
  - POST to the new ingest-api `Papers` [POST endpoint in ingest-api](https://github.com/hubmapconsortium/ingest-api/issues/289)
  - authorization to create/save by user group works the same as other entities, a user needs to be in a "write group" to create and a user needs to belong to the same group as the entity to edit
  - allow edit/save only if the Paper.status is not "Published"
  - on create if a user belongs to multiple "write groups" pop up the dialog to ask which group to assign the `Paper` to
  - On edit, if not in Published state only enable a "Save" button, no other action buttons.
  - After a create/POST show the same information in the modal as a `Dataset` create, the HuBMAP ID and the Globus link.
  - On edit show the Globus link at the top of the form, the same as `Dataset` edit form

**Comment by BirdMachine** [comment]
[Doc With Mockups](https://docs.google.com/document/d/1wQxP3JMmPAgkFSmOajiVuGibGIUCRLh4LJlV4FCp6LI/edit?pli=1#heading=h.8jpk451j74b8 )
![Screenshot_20230221_142941](https://user-images.githubusercontent.com/8226070/220440643-e03c01e6-6ab1-4ee7-8ef3-bd9cec81021f.png)
