### ISSUE TITLE
Publication UI/Buttons for workflow

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/ingest-ui#1055]
On the Publication update form show the following buttons under the following conditions:
  - Submit: User is a member of the "Data Admin" group and `status == New`
  - Save: User has write access and `status == New`
  - New Version: User has write access and `status == Published`
  
  Otherwise only show the Cancel button.

**Comment by BirdMachine** [comment]
Submit: User is a member of the "Data Admin" group and status == New
Save: User has write access and status == New
    
    So do we have: 
    (*Only = Ignoring Versioning & Cancel)
        
        - Admins Only* have access to ingest_api_dataset_submit in a Submit button
            - Meaning NO access to entity_api_update_entity, NO SAVE button
        
        - Users Only* have access to entity_api_update_entity to update/Save 
            - meaning NO access to ingest_api_dataset_submit, NO submit button
        
    Is this reflected in BOTH the NEW form as well as the EDIT form? 
        - Who is allowed to CREATE a Publication?
        - What does that button say?
        - Does it go to ingest_api_create_publication, or somewhere elese?
    
    
New Version: User has write access and status == New 
    - New versions are only available on Non-new, Published datasets? Is this a reversal of that? Are versions still Allowed?

**Comment by shirey** [comment]
@BirdMachine My original message was only meant for Update screen not Create-- save/cancel buttons should remain as is on Create screen.

I forgot about the versioning button- the rule on the Update screen for showing the "New Version" (or whatever we call it..not sure) is: Show versioning button if `status == Published` and user has write access

The definition of "write access" when creating is the user having any membership in a Data Provider group (group property `data_provider == true`)  The definition of "write access" for updates is membership in the group that owns/created the entity (is this how we do it on other entity's update screens??)

**Comment by BirdMachine** [comment]
For write access I ping 
${process.env.REACT_APP_METADATA_API_URL}/entities/${uuid}/allowable-edit-states
And for the access status without State, {process.env.REACT_APP_METADATA_API_URL}/entities/${uuid}/allowable-edit-states?ignore-publication-status=true
