### ISSUE TITLE
Store file information and update metadata on dataset status update

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/ingest-ui#106]
Extend the /datasets/status endpoint to accept a list of file attributes to be stored in the metadata of a dataset.  The file attributes will be an array like:

```
files: [{ "relativePath" : "/path/to/file/example.txt",
           "type":"filetype",
           "size":filesize,
           "checksum":"file-checksum"
         }]
```

**Comment by cborromeo** [comment]
I need to get some sample data from Joel to ensure this works.  The Codex data would be a good test.

**Comment by cborromeo** [comment]
@shirey Please note this is dependent on getting data from Joel's CODEX Airflow system.

**Comment by cborromeo** [comment]
I made some changes based on the code below: 

```
files: [{ "relativePath" : "/path/to/file/example.txt",
           "type":"filetype",
           "size":filesize,
           "checksum":"file-checksum"
         }]
```

These changes are checked into the codex_sprint_202002 branch.
