### ISSUE TITLE
Change invalid message and persistence for Publication source

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/ingest-ui#1071]
If, on creation, no Source is added for a Publication and the "Save" button is pressed, the UI correctly recognizes it as invalid.
  - The current message displayed is "is-invalid", change this to "Invalid Source: At least one source must be added."
  - After a source is added and the "Save" button is pressed again remove the message (this happens for all other validation messages).

**Comment by BirdMachine** [comment]
Also Addresses #1083

**Comment by shirey** [comment]
@BirdMachine Reviewed on TEST, looks good now.  Closing.
