### ISSUE TITLE
Use ontology for Organ and Data Type lists

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/ingest-ui#1077]
Instead of the current methods (hard coded or read from .yaml file via search-api) to fill the Organ Type (Sample form) and Data Type (Dataset form) field dropdowns, source the information via the UBKG service from the HuBMAP Application Ontology.

Lacking a UBKG service that I can make modifications to, I have been working on writing the server API stubs and mocking them for testing purposes. Jes and I have tested the integration, so that when the endpoints in UBKG are created they just need to be added to the UBKG server stub and retested.

The UBKG endpoints have been created, but need to be run on DEV.

UBKG is running on DEV. Worked with Jes and it looks good locally. Created a Pull request for this work on ingest-ui https://github.com/hubmapconsortium/ingest-ui/pull/1097

This was tested and merged with main https://github.com/hubmapconsortium/ingest-ui/pull/1099 the corresponding pull request from ubkg-api was merged with main https://github.com/x-atlas-consortia/ubkg-api/pull/28

**Comment by AlanSimmons** [comment]
@shirey I may have gotten ahead of myself. This is in ingest-ui instead of UBKG, so I should not have moved it.
