### ISSUE TITLE
Cancel button doesn't work on group selection modal

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/ingest-ui#1082]
When creating a new Publication, when the dialog pops up to select a group (for users belonging to multiple groups who can register/write) selecting the Cancel button does nothing.

<img width="555" alt="image" src="https://user-images.githubusercontent.com/5816400/227063188-06537ed4-68ee-4f13-b0ae-20fbe5a8712c.png">

**Comment by BirdMachine** [comment]
Duplicate of #1080

**Comment by BirdMachine** [comment]
Duplicate of #1080 and Im bad at Github.

**Comment by BirdMachine** [comment]
Dupe of #1080 (and marked properly again as such)

**Comment by BirdMachine** [comment]
Dupe #1080
