### ISSUE TITLE
Remove "Source ID" field from UI

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/ingest-ui#114]
Talked with @cborromeo :

- The data in `source_uuid` (which it populates) is hopelessly messy.
- We can get what we need from other sources.

So we think it'd be best to drop it from the form.

(This conversation began in hubmapconsortium/entity-api#17)

**Comment by shirey** [comment]
Closing.  This id messiness has been since cleaned up (a bit...)...
