### ISSUE TITLE
Bulk Registration Bug + Blank Screen

### ISSUE THREAD

**Issue by bhonick** [hubmapconsortium/ingest-ui#1190]
## Bug report

__Help Desk Issue Tracker URL__: # 3850

__Message__: 

A data provider attempted to bulk register several donors. However, when clicking the "Upload" button to share their TSV file, they found that no submission dialog would appear. Rather, the webpage would become totally blank. I have replicated this bug on my end and will share a recording via Slack.

**Comment by yuanzhou** [comment]
Adding the recording that @bhonick had shared on Slack to this issue 
![Peek 2023-07-27 09-53](https://github.com/hubmapconsortium/ingest-ui/assets/195873/0bf00974-47d3-46fc-bed6-ee73b5591291)

**Comment by shirey** [comment]
@bhonick Is there a particular TSV that we can use to replicate?  If so, please add here.

**Comment by bhonick** [comment]
@shirey [tmc-ucsd-repro-donors-20230804.csv](https://github.com/hubmapconsortium/ingest-ui/files/12263333/tmc-ucsd-repro-donors-20230804.csv)

**Comment by shirey** [comment]
@bhonick FYI- this issue here was that the selection_protocol field in the tsv needed the `https://` on the front of the urls to pass our initial validation, but there was a bug causing the resulting error message(s) not to display.  The fix for this should be released later today.
