### ISSUE TITLE
Data Providers Have Ability to Validate Uploads

### ISSUE THREAD

**Issue by bhonick** [hubmapconsortium/ingest-ui#1193]
Earlier this afternoon, a data provider was able to click the `Validate` button for an upload. This breaks the curation workflow. Providers should not be able to access this tool, and they should only have the ability to press the `Submit` button.

**Comment by shirey** [comment]
@bhonick Should the validate button be removed entirely or should folks with admin access be allowed to see/press it?

**Comment by bhonick** [comment]
@shirey It should be only accessible to those with admin access, since I need it for curation. Thanks!

**Comment by bhonick** [comment]
@shirey I'm not sure how to check this, since I only have access to my individual user account.

**Comment by shirey** [comment]
@bhonick The above comment asking for the check wasn't meant for you, but as a reminder for me...  @BirdMachine Please ensure that the Validate button on the Uploads screen only appears for members of the `HuBMAP-Data-Admin` group.
