### ISSUE TITLE
Multiple matched search results for the given unique HuBMAP ID

### ISSUE THREAD

**Issue by yuanzhou** [hubmapconsortium/ingest-ui#1194]
Reported by Diane at PSC from a user submitted help ticket:
>We have a help desk ticket from Stephen Fisher regarding the search feature in Ingest.
Why does the ingest portal search return 20 hits to my HuBMAP ID query? This ID is for a donor I just registered for Penn and has no relation to Vanderbilt group. Are the IDs not unique?
HBM446.CSSP.335

Below is the search query issued from the ingest-ui to search-api, it uses `multi_match` against multiple `fields` which is resulting multiple records.

```
{
  "query": {
    "bool": {
      "must": {
        "match": {
          "entity_type": "Donor OR Sample OR Dataset OR Upload OR Publication"
        }
      },
      "filter": {
        "multi_match": {
          "query": "HBM446.CSSP.335",
          "fields": [
            "description.keyword",
            "hubmap_id.keyword",
            "submission_id.keyword",
            "display_doi.keyword",
            "lab_donor_id.keyword",
            "display_subtype.keyword",
            "lab_name.keyword",
            "lab_tissue_sample_id.keyword",
            "lab_donor_id.keyword",
            "lab_dataset_id.keyword",
            "created_by_user_displayname",
            "created_by_user_email",
            "dataset_info"
          ]
        }
      }
    }
  },
  "from": 0,
  "size": 100,
  "sort": [
    {
      "last_modified_timestamp": "asc"
    }
  ],
  "_source": [
    "created_by_user_displayname",
    "hubmap_id",
    "submission_id",
    "computed_lab_id_type",
    "display_subtype",
    "group_name",
    "created_by_user_email",
    "lab_donor_id",
    "lab_tissue_sample_id",
    "entity_type",
    "specimen_type",
    "organ",
    "lab_dataset_id",
    "data_access_level",
    "status",
    "uuid",
    "title"
  ]
}
```

**Comment by shirey** [comment]
@BirdMachine In previous versions we had this worked out such that if there was a single keyword search argument provided and this argument matched an id field (hubmap_id or submission_id, I believe, but not uuid..?), then only the record for the entity with the matching id was displayed.  This was done either with a different query or by post processing the results of the query to search for a record with the matching id.
