### ISSUE TITLE
Bogus HuBMAP identifiers

### ISSUE THREAD

**Issue by cborromeo** [hubmapconsortium/ingest-ui#120]
Users can produce "bogus" HuBMAP identifiers like: TEST0027-1 or TEST0016-2.  The system should not allow an id like TEST0016-2.  This identifier implies that a sample is directly produced from a donor (it should include an organ identifier like BL, RL, RK, etc.)  This occurs when a user is attempting to register an organ for a Donor sample.  Here are the steps to reproduce:

1.  create a new donor 
2.  click the "register an organ from this donor" button  3.  select the organ 
4. change the "Tissue Sample Type" to something other than organ.  
5.  Fill out the rest of the form.  
6. click "Generate ID".

**Comment by shirey** [comment]
Closing.  This is no longer possible with the reworked UI that matches the refactored data schema.
