### ISSUE TITLE
Pop-up on Collection Submit

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/ingest-ui#1208]
Can the pop-up after Submit on a new collection be eliminated?  I think it wanted to bring up the Globus directory in a new tab, which isn't needed.
![image](https://github.com/hubmapconsortium/ingest-ui/assets/5816400/00d63a31-afba-42d2-8dca-df572e3bc168)

**Comment by BirdMachine** [comment]
Non-reproduceable
