### ISSUE TITLE
Wireframe to handle multiple versions

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/ingest-ui#1231]
Create a wireframe/example layout for approval before creating the actual user interface that will exposed multiple previous and/or next versions of Datasets and Publications.  Currently we only allow one previous_revision and one next_revision of a Dataset or Publication.  Moving forward we will allow multiple previous or next revisions of datasets and publications.

A simple design that would replace the current next/previous links with pop-up models or dropdowns or something when there are multiple revisions seems reasonable, but let's explore with a wireframe before implementing Backend support isn't finished yet (hasn't been started) anyway.

**Comment by BirdMachine** [comment]
![Screenshot_20231002_091318](https://github.com/hubmapconsortium/ingest-ui/assets/8226070/44f8d7a6-3385-4e7b-a850-22e4efdbf439)
