### ISSUE TITLE
Add RUI_Location to Donors and Samples

### ISSUE THREAD

**Issue by cborromeo** [hubmapconsortium/ingest-ui#126]
The researchers are collecting information covered by a RUI.  This describes where the specimen exists in three dimensional space.  We need to add an attribute called rui_location to the donors and specimens.  This attribute will store a JSON string.

**Comment by cborromeo** [comment]
I have inserted the data into the production neo4j system.  Here are the 16 specimens I have updated:


dataset_doi | sample_id
"HBM336.FWTN.636" | "UFL0001-SP-3-4"
"HBM749.WHLC.649" | "UFL0001-SP-1-3"
"HBM556.QMSM.776" | "UFL0001-SP-2-8"
"HBM472.NTNN.543" | "UFL0002-SP-2-2"
"HBM396.RPRR.624" | "UFL0003-SP-2-2"
"HBM984.GRBB.858" | "UFL0004-SP-2-1"
"HBM558.SRZG.629" | "UFL0002-SP-3-4-1"
"HBM432.LLCF.677" | "UFL0001-SP-2-5-1"
"HBM267.BZKT.867" | "UFL0003-SP-2-6-1"
"HBM633.CLVN.674" | "UFL0003-SP-3-6-1"
"HBM839.VWVF.894" | "UFL0001-SP-3-8-1"
"HBM355.JDLK.244" | "UFL0004-SP-2-4-1"
"HBM427.SMGB.866" | "UFL0004-SP-1-4-1"
"HBM987.XGTH.368" | "UFL0002-SP-2-4-1"
"HBM647.MFQB.496" | "UFL0001-SP-1-2-1"
"HBM244.TJLK.223" | "UFL0003-SP-1-4-1"

**Comment by shirey** [comment]
Closing.  This was completed for Samples (not needed for Donors).
