### ISSUE TITLE
Add "Upload Sample Metadata" functionality

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/ingest-ui#1263]
Add a new dropdown menu "Upload Sample Metadata" to allow users to add Sample metadata for Blocks, Suspensions and Sections. (for samples already registered)

This functionality should work similarly to the current functionality in SenNet and will use the recently created [/metadata/validate endpoint](https://github.com/hubmapconsortium/ingest-api/issues/384)

![image](https://github.com/hubmapconsortium/ingest-ui/assets/5816400/85fd739a-1974-4d8c-9ccb-27603db17234)

**Comment by BirdMachine** [comment]
Note: 
Uploading the [legacy example.tsv](https://data.dev.sennetconsortium.org/bulk/metadata/example_sample_block_metadata.tsv) in Sennet validates, but through the same process on hubmap, we get a 500 error "description": "'set' object has no attribute 'items'",
Are we intending to support this format on hubmap as well?
