### ISSUE TITLE
Whitespace before after keyword or id search fails

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/ingest-ui#1274]
When doing a keyword search if you include a white space before or after an ID the search will fail example:
![image](https://github.com/hubmapconsortium/ingest-ui/assets/5816400/e8f652ee-555d-49f5-bb04-af0fb3401a2c)
vs
![image](https://github.com/hubmapconsortium/ingest-ui/assets/5816400/3e21b433-da01-4062-ace3-f926e0dd7b29)

**Comment by BirdMachine** [comment]
Cannot replicate (for example works with [Multiple spaces before and after](https://ingest.hubmapconsortium.org/?keywords=++HBM638.HMDC.533+))
Seemingly addressed in PR #1282
