### ISSUE TITLE
Add `Assigned to Group Name` dropdown and `Ingest Task` text field to Datasets and Uploads

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/ingest-ui#1277]
On both the Upload and Dataset edit screens show and allow the following fields to be edited when the user is in the data_admin group otherwise if the user in not in the data_admin group do not show these fields:

  - `Assigned to Group Name` Dropdown containing the `shortname` version of all the groups where the group is `data_provider == true` (I think this is the same as the search "Group" dropdown)-- PLUS one extra "empty" entry at the top to allow users to clear the field. Description/Help text: The group responsible for the next step in the data ingest process.
  - `Ingest Task` Text field, no validation needed.  Description/Help text: The next task in the data ingest process.

**Comment by BirdMachine** [comment]
Feedback Details: 
- For Uploads, once the entity is no longer editable, do not include the Task Assignment UI
- For Datasets, do keep the Task Assignment UI even if the entity itself is otherwise no longer editable
