### ISSUE TITLE
Directory uuid changes if editing Donor/Samples

### ISSUE THREAD

**Issue by cborromeo** [hubmapconsortium/ingest-ui#128]
If a user edits a Donor or Sample, the edit generates a new directory on the file system.  For example, a user generates the Donor initially with a directory <TMC uuid>/<donor_uuid>.  When the user edits this donor, the edits move any new files into <TMC uuid>/<metadata_uuid>.  The expected behavior should keep the directory <TMC uuid>/<donor_uuid> in both cases.

**Comment by shirey** [comment]
Closing.  This is no longer an issue with the new/refactored data schema.
