### ISSUE TITLE
Add parent IDs to dataset records in UUID system

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/ingest-ui#129]
When generating a UUID for a Dataset include the parent entity id.  Also, backfill all existing parent ids in UUID databases.

**Comment by cborromeo** [comment]
@shirey  This is represented as an array in the metadata node for the dataset. 
for example:
"source_uuid": "['TEST0010-LK-1-1']"

Do I need to move this to the entity node?

**Comment by shirey** [comment]
I think it makes sense to leave it in the metadata node because over time if it changes (not sure if this makes sense, but may if there was a data entry error) we'll be able to track the change when we get the metadata node versioning in place.

I think the name "source_uuid" should be changed to "source_display_id", though...maybe that is part of another ticket, though, as it will require changes (in UI and) elsewhere.

**Comment by cborromeo** [comment]
@shirey Thanks Bill.  I think renaming the source_uuid is part of Chuck's https://github.com/hubmapconsortium/entity-api/issues/17 issue.  I will try to change this to source_display_id in both the back end and the UI.  
On a related note, source_uuid is also found in samples and refers to their parent ids.  I am assuming you want me to change the field for both datasets and samples.  Is this correct?

**Comment by cborromeo** [comment]
These changes were committed to a 1.9 derived branch called 1.9_cdb_features.  I didn't want to distrupt the testing on the atacseq_sprint branch.  I need to add the dataset changes to the create_derived_dataset code in the atacseq_sprint branch.

**Comment by shirey** [comment]
Thanks. Yes, let's hold this for the next release (not 1.9) and probably (hopefully) the atacseq branch.

**Comment by cborromeo** [comment]
As part of the deployment, we need to run these Cypher queries:

MATCH (e) WHERE EXISTS(e.source_uuid) 
SET e.source_display_id = e.source_uuid
RETURN e.uuid, e.source_uuid, e.source_display_id

MATCH (e) WHERE EXISTS(e.source_display_id) 
REMOVE e.source_uuid
RETURN e.uuid, e.source_uuid, e.source_display_id
