### ISSUE TITLE
Switch out drop down for `data_types` to `dataset_type`

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/ingest-ui#1297]
The `Dataset.data_types` field will be deprecated soon and the new `Dataset.dataset_type` field will be required at that time.  To support this switch out the current drop down on the Dataset create/edit page tied to `data_types` to read/populate `dataset_types`.  The list of allowable `dataset_types` is available from: https://ontology.api.hubmapconsortium.org/valueset?parent_sab=HUBMAP&parent_code=C003041&child_sabs=HUBMAP

Do this work and test, but hold it (don't release) in a branch named: soft-assay-conversion as it will need to be released in coordination with other changes across other services/applications.

**Comment by BirdMachine** [comment]
Additional work to support the new dataset_type is being tracked in #1302 and #1303
