### ISSUE TITLE
Basic wireframe design for EPIC objects

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/ingest-ui#1315]
Create a wireframe showing a screen to create/edit the new EPIC entity types.

EPIC entities will be modeled EXACTLY like Publications, where they will be a subclass of Dataset with Datasets allowed as direct ancestors/parents/sources and some new fields associated with them.

**Comment by shirey** [comment]
@BirdMachine @yuanzhou Just a drawing for this, please...no need to code into the UI yet as we may end up changing it A LOT.  For the "extra new fields", we do not have a list of these yet, so just put a few placeholders there.  BUT-- this EPIC will work exactly like a Publication with Dataset ancestors and other fields shown that are common to Datasets.

**Comment by yuanzhou** [comment]
FYI @BirdMachine 
>An EPIC is an Externally Processed Integrated Collection. These are data that are processed outside of the HIVE (probably by a Data Provider/TMC type group) and provided to us.
