### ISSUE TITLE
Refinements to Revert Function

### ISSUE THREAD

**Issue by bhonick** [hubmapconsortium/ingest-ui#1384]
@shirey @BirdMachine I have a few requests for status modification/the blame mechanism (assigned to group name/ingest task) on Ingest UI. 

- Could the `revert` button be added to New/Submitted/Invalid entities?

**Comment by BirdMachine** [comment]
1) Yes, that should be well within doability. Do we know the specific conditions to render? (IE, Must Be Incomplete AND user Must Have (Editing/Admin/Reverting/ETC) Permissions)
2) Also sounds very doable, will need to research how it is on SenNet now for specifics to confirm. Safe to assume the same conditions apply as above?

**Comment by bhonick** [comment]
@BirdMachine Thanks! I'll create a second card per Bill's request. For number 1, the revert button should render for only data admins, and it should be visible for all non-published/non-reorganized datasets/uploads. Some screenshots from the SenNet portal are below.

![image](https://github.com/hubmapconsortium/ingest-ui/assets/71984404/bcac71e5-c61a-4c55-b5c2-fa870b3c87d6)

![image](https://github.com/hubmapconsortium/ingest-ui/assets/71984404/ee40aa59-bfaa-4fa8-bbf2-223c701e2c9d)

![image](https://github.com/hubmapconsortium/ingest-ui/assets/71984404/1e485f0a-8b49-43ac-a32d-7d1d9ba71bad)
