### ISSUE TITLE
Make Incomplete Status Yellow on Data Ingest Board

### ISSUE THREAD

**Issue by bhonick** [hubmapconsortium/ingest-ui#1387]
@shirey @DerekFurstPitt Please change the color of the `Incomplete` status on the Data Ingest Board from gray to yellow to match the color used on the Ingest UI:

![image](https://github.com/hubmapconsortium/ingest-ui/assets/71984404/d85e8769-f5cb-4cb4-ba95-31e71b8ca087)
![image](https://github.com/hubmapconsortium/ingest-ui/assets/71984404/d1ca2ee5-deed-4f04-94f6-b8a8303cd26d)

**Comment by shirey** [comment]
@bhonick This is the wrong repo to create this card.  It needs to be created in: https://github.com/x-atlas-consortia/data-ingest-board.  Unfortunately you can't automatically transfer issues across GitHub organizations, so you'll need to recreate it over there.  I'm going to close it here.

**Comment by bhonick** [comment]
@shirey Thanks!
