### ISSUE TITLE
Example TSV for metadata upload not found

### ISSUE THREAD

**Issue by yuanzhou** [hubmapconsortium/ingest-ui#1414]
<img width="1128" alt="Screenshot 2024-05-23 at 10 21 29 AM" src="https://github.com/hubmapconsortium/ingest-ui/assets/195873/d156bf84-e791-4060-9c35-cf994ad1639e">

**Comment by shirey** [comment]
@BirdMachine This appears to still be broken on DEV/TEST/PROD
