### ISSUE TITLE
Bulk Metadata Upload Error Capture Upgrades

### ISSUE THREAD

**Issue by BirdMachine** [hubmapconsortium/ingest-ui#1417]
The Responses from the API have changed somewhat from before, and the error content is wrapped differently in some cases. Need to re-align with the API expectations

**Comment by shirey** [comment]
@BirdMachine (FYI @yuanzhou ) The attached file, when uploaded as Block metadata contains one error (an invalid value in the `source_storage_duration_unit` column.  Based on the json returned from the validator (see response json pasted below) the message to the user should be something like:
<img width="948" alt="image" src="https://github.com/hubmapconsortium/ingest-ui/assets/5816400/8840dfa3-01fc-4629-8fd1-608fe4a3020c">


But currently is rendered like:
<img width="953" alt="image" src="https://github.com/hubmapconsortium/ingest-ui/assets/5816400/1fd8166c-feca-4de5-80ed-d20bab225df4">


Response JSON
```
{
  "code": 406,
  "description": [
    {
      "column": "source_storage_duration_unit",
      "error": "On row 1, column \"source_storage_duration_unit\", value \"ms\" fails because of error \"notStandardTerm\". Example: minute",
      "row": 1
    }
  ],
  "name": "Unacceptable Metadata"
}
```

**Comment by shirey** [comment]
@BirdMachine Also the links to the example .tsv fiiles for Block, Section and Suspension point to the example contributors.tsv file instead of the examples for block, section and suspension.

**Comment by BirdMachine** [comment]
> [sample-block-bad-storage_source_duration_unit.tsv.txt](https://github.com/user-attachments/files/16012898/sample-block-bad-storage_source_duration_unit.tsv.txt)

So regarding this situation, this is how pre-attachment validation currently exists on Prod (assuming, using Test as the reference). The Point of the task was to handle the **attachment** responses, not the initial cedar validation responses. Have you had a moment to check the response formatting for an uploaded csv that passes Validation but Fails (fully or partially) on the Attachment Step? 
I'll create a new ticket item for updating the Cedar validation responses as well. 
It'd be worth time coordinating with someone on the API end and get full documentation/reference/information for **every** possible _formatting_ and _wrapping_ error variation possible.
