### ISSUE TITLE
Special handling for datasets with a large number of direct ancestors

### ISSUE THREAD

**Issue by yuanzhou** [hubmapconsortium/ingest-ui#1420]
As a result of https://github.com/hubmapconsortium/search-api/issues/788, we'll have Datasets with a large number (hundreds or even thousands) of direct ancestors. The button to edit the sources and the delete action (trash bin icon) on each source should be disabled. When editing other fields and submit the updates, `direct_ancestor_uuids` field should NOT be included in the request payload either.

For example: https://ingest.dev.hubmapconsortium.org/dataset/9dc2de0838a4fd3e960b35424788950d has 2500 direct ancestors.

<img width="1168" alt="Screenshot 2024-06-10 at 11 34 37 PM" src="https://github.com/hubmapconsortium/ingest-ui/assets/195873/a1a7e21f-227d-4686-988c-7c481e1951ed">

### Questions: ###
- Cases like this, all the direct ancestors will be Datasets and none has "Submission ID", can we remove that column?
- Is there a way that we can identify such datasets by type?
- Can we use some special UI theme to make such datasets obvious to the users?

**Comment by shirey** [comment]
We won't do this right now, closing
