### ISSUE TITLE
Assigned to Group Name/Ingest Task Fields Missing from Uploads in Incomplete Status

### ISSUE THREAD

**Issue by bhonick** [hubmapconsortium/ingest-ui#1424]
@shirey I noticed an issue on Ingest UI. Uploads in the `New` status have the assigned to group name/ingest task fields visible. However, uploads in the `Incomplete` status do not have those controls, although the `Revert` toggle is present. Please see the below screenshots.

![image](https://github.com/hubmapconsortium/ingest-ui/assets/71984404/7dda29d0-0e5b-45cd-953e-903181e644d0)

![image](https://github.com/hubmapconsortium/ingest-ui/assets/71984404/3fb766c2-4fc7-4208-bc94-ebb4373655a2)

**Comment by libpitt** [comment]
@bhonick Just to confirm, the ask is to make the `Ingest Task` and `Assigned To Group Name` fields available and editable/writeable to the data admin, yes? 
And second confirmation, the `Upload Title` and `Description` fields, are these to remain uneditable in `Incomplete` status?

**Comment by bhonick** [comment]
@libpitt the `Ingest Task` and `Assigned To Group Name` are already editable/writeable by the data admins. The issue presented is that on Ingest UI pages like the ones displayed in the above screenshots, the UI controls for modifying those values are not present (see the first screenshot compared to the second one). I can still update those values using an API call or the bulk_update_entities DAG, but having those controls available on Ingest UI would be ideal.

**Comment by libpitt** [comment]
@bhonick Thanks! What I was asking is if the task is to make these fields available for edit, including the `Upload Title` and `Description`. The screen below shows what was done. 


![all-fields-editable](https://github.com/user-attachments/assets/7fe393df-ea51-495e-ad4d-785324f2d3fa)

**Comment by bhonick** [comment]
@libpitt Yep, that's great, thanks!
