### ISSUE TITLE
Bulk Add UUID Issue on Collection Page

### ISSUE THREAD

**Issue by bhonick** [hubmapconsortium/ingest-ui#1437]
@shirey I tried using the bulk add UUID feature on the collection page (https://ingest.hubmapconsortium.org/new/collection) on Ingest UI, but I am getting the following error. This occurs with both HuBMAP IDs and UUIDs.

Here is the list of UUIDs:
de73b015aafc46e9c7f873457c02fea0,fd7bf5a22d021017a82bf2b83efe52d2,d37e5fe90ddf9f2535a913cc415f4fe7,f10f59f196b3e53c70b5b58f9012e36a,8d51fc582c00160bec23e65a80600582,8d36a15ae420bd07ec13c4a7b280d8e6,c3c91e3f720ecaebb9d8bf8b9ce4451c,7c88708f5faefa676207bfb7a9c33d10,029cb9dcaf9138a3f1040cba016ac0a2,08025cc1ff0222c68f98858a27d759be,e739032bebb1bd2fd5546e1ba61cce2f,ba64d86ff29e92859ba0a8e802c142e7

![image](https://github.com/user-attachments/assets/c7b43c43-068f-4d53-a082-44b6627cec0f)

Stack Trace Output:
Error: MUI: The data grid component requires all rows to have a unique `id` property. Alternatively, you can use the `getRowId` prop to specify a custom id for each row. A row was provided without id in the rows prop: {"contacts":[{"affiliation":"University of California, San Diego","display_name":"Kun Zhang","email":"","first_name":"Kun","is_contact":"Yes","is_operator":"No","is_principal_investigator":"No","last_name":"Zhang","metadata_schema_id":"94dae6f8-0756-4ab0-a47b-138e446a9501","middle_name_or_initial":"","orcid":"0000-0002-7596-5224"},{"affiliation":"University of California, San Diego","display_name":"Blue B. Lake","email":"","first_name":"Blue","is_contact":"Yes","is_operator":"No","is_principal_investigator":"No","last_name":"Lake","metadata_schema_id":"94dae6f8-0756-4ab0-a47b-138e446a9501","middle_name_or_initial":"B","orcid":"0000-0002-8637-9044"}],"contains_human_genetic_sequences":true,"contributors":[{"affiliation":"University of California, San Diego","display_name":"Kun Zhang","email":"","first_name":"Kun","is_contact":"Yes","is_operator":"No","is_principal_investigator":"No","last_name":"Zhang","metadata_schema_id":"94dae6f8-0756-4ab0-a47b-138e446a9501","middle_name_or_initial":"","orcid":"0000-0002-7596-5224"},{"affiliation":"University of California, San Diego","display_name":"Blue B. Lake","email":"","first_name":"Blue","is_contact":"Yes","is_operator":"No","is_principal_investigator":"No","last_name":"Lake","metadata_schema_id":"94dae6f8-0756-4ab0-a47b-138e446a9501","middle_name_or_initial":"B","orcid":"0000-0002-8637-9044"},{"affiliation":"University of California, San Diego","display_name":"Dinh H. Diep","email":"","first_name":"Dinh","is_contact":"No","is_operator":"Yes","is_principal_investigator":"No","last_name":"Diep","metadata_schema_id":"94dae6f8-0756-4ab0-a47b-138e446a9501","middle_name_or_initial":"H","orcid":"0000-0001-6057-4119"},{"affiliation":"University of California, San Diego","display_name":"Thu Duong","email":"","first_name":"Thu","is_contact":"No","is_operator":"No","is_principal_investigator":"No","last_name":"Duong","metadata_schema_id":"94dae6f8-0756-4ab0-a47b-138e446a9501","middle_name_or_initial":"","orcid":"0000-0001-7122-4448"},{"affiliation":"University of Rochester Medical Center","display_name":"Gloria Pryhuber","email":"","first_name":"Gloria","is_contact":"No","is_operator":"No","is_principal_investigator":"Yes","last_name":"Pryhuber","metadata_schema_id":"94dae6f8-0756-4ab0-a47b-138e446a9501","middle_name_or_initial":"","orcid":"0000-0002-9185-3994"},{"affiliation":"University of Rochester Medical Center","display_name":"Heidie Huyck","email":"","first_name":"Heidie","is_contact":"No","is_operator":"No","is_principal_investigator":"No","last_name":"Huyck","metadata_schema_id":"94dae6f8-0756-4ab0-a47b-138e446a9501","middle_name_or_initial":"","orcid":"0000-0001-9453-0747"},{"affiliation":"University of Rochester Medical Center","display_name":"Ravi Misra","email":"","first_name":"Ravi","is_contact":"No","is_operator":"No","is_principal_investigator":"No","last_name":"Misra","metadata_schema_id":"94dae6f8-0756-4ab0-a47b-138e446a9501","middle_name_or_initial":"","orcid":"0000-0002-1352-4378"},{"affiliation":"Harvard medical school","display_name":"Peter V. Kharchenko","email":"","first_name":"Peter","is_contact":"No","is_operator":"No","is_principal_investigator":"No","last_name":"Kharchenko","metadata_schema_id":"94dae6f8-0756-4ab0-a47b-138e446a9501","middle_name_or_initial":"V","orcid":"0000-0002-6036-5875"},{"affiliation":"Harvard medical school","display_name":"Jenny Dong","email":"","first_name":"Jenny","is_contact":"No","is_operator":"No","is_principal_investigator":"No","last_name":"Dong","metadata_schema_id":"94dae6f8-0756-4ab0-a47b-138e446a9501","middle_name_or_initial":"","orcid":"0000-0003-1059-5653"},{"affiliation":"University of California, San Diego","display_name":"Kimberly Conklin","email":"","first_name":"Kimberly","is_contact":"No","is_operator":"No","is_principal_investigator":"No","last_name":"Conklin","metadata_schema_id":"94dae6f8-0756-4ab0-a47b-138e446a9501","middle_name_or_initial":"Y","orcid":"0000-0001-8141-064X"}],"created_by_user_displayname":"HuBMAP Process","created_by_user_email":"hubmap@hubmapconsortium.org","created_by_user_sub":"3e7bce63-129d-33d0-8f6c-834b34cd382e","created_timestamp":1720625810745,"creation_action":"Create Dataset Activity","data_access_level":"protected","dataset_type":"SNARE-seq2","description":"Lung SNARE-seq2 RNAseq and ATAC libraries for LAPMAP_20211020I : ./LAP240","direct_ancestors":[{"created_by_user_displayname":"Anthony Corbett","created_by_user_email":"Anthony_Corbett@URMC.Rochester.edu","created_by_user_sub":"b4a08f60-d274-11e5-989f-4b82619d2bbe","created_timestamp":1693506779546,"data_access_level":"consortium","description":"single nuclei from tissue curls ","entity_type":"Sample","group_name":"University of California San Diego TMC","group_uuid":"03b3d854-ed44-11e8-8bce-0e368f3075e8","hubmap_id":"HBM826.DFLL.937","lab_tissue_sample_id":"D231-RML-10B2-2-1","last_modified_timestamp":1693506779546,"last_modified_user_displayname":"Anthony Corbett","last_modified_user_email":"Anthony_Corbett@URMC.Rochester.edu","last_modified_user_sub":"b4a08f60-d274-11e5-989f-4b82619d2bbe","protocol_url":"https://dx.doi.org/10.17504/protocols.io.bh26j8he","sample_category":"suspension","submission_id":"UCSD0022-RL-5-1-1","uuid":"2d1ebed1dffb7790eea48effb2f1784b"}],"entity_type":"Dataset","group_name":"University of California San Diego TMC","group_uuid":"03b3d854-ed44-11e8-8bce-0e368f3075e8","hubmap_id":"HBM277.LMQQ.328","ingest_metadata":{"dag_provenance_list":[{"hash":"eba4dfa","origin":"https://github.com/hubmapconsortium/ingest-pipeline.git"}],"extra_metadata":{"collectiontype":"multiassay_metadatatsv"},"files":[],"metadata":{"contributors_path":"extras/lapmap_2022_snare2.tsv","data_path":".","dataset_type":"SNARE-seq2","lab_id":"LAP240","metadata_schema_id":"b76e54fe-5352-449b-9188-f250b51fbedc","number_of_pre_amplification_pcr_cycles":"","parent_sample_id":"HBM826.DFLL.937","preparation_protocol_doi":"https://dx.doi.org/10.17504/protocols.io.bzdsp26e"},"thumbnail_file_abs_path":[]},"last_modified_timestamp":1721136553544,"last_modified_user_displayname":"HuBMAP Process","last_modified_user_email":"hubmap@hubmapconsortium.org","last_modified_user_sub":"3e7bce63-129d-33d0-8f6c-834b34cd382e","local_directory_rel_path":"protected/University of California San Diego TMC/de73b015aafc46e9c7f873457c02fea0/","pipeline_message":"the process ran","provider_info":"LAPMAP_20211020I SNAREseq2 : ./LAP240","status":"Submitted","status_history":[{"change_timestamp":1720625810745,"changed_by_email":"hubmap@hubmapconsortium.org","status":"New"},{"change_timestamp":1720625871120,"changed_by_email":"hubmap@hubmapconsortium.org","status":"Submitted"},{"change_timestamp":1720626027996,"changed_by_email":"hubmap@hubmapconsortium.org","status":"Error"},{"change_timestamp":1721136553544,"changed_by_email":"hubmap@hubmapconsortium.org","status":"Submitted"}],"title":"SNARE-seq2 data from the lung (right) of a 33-year-old black or african american female","upload":{"created_by_user_displayname":"Anthony Corbett","created_by_user_email":"Anthony_Corbett@URMC.Rochester.edu","created_by_user_sub":"b4a08f60-d274-11e5-989f-4b82619d2bbe","created_timestamp":1705007218869,"description":"Lung SNARE-seq2 RNAseq and ATAC libraries for LAPMAP_20211020I","entity_type":"Upload","group_name":"University of California San Diego TMC","group_uuid":"03b3d854-ed44-11e8-8bce-0e368f3075e8","hubmap_id":"HBM283.BBHV.267","last_modified_timestamp":1720625869210,"last_modified_user_displayname":"HuBMAP Process","last_modified_user_email":"hubmap@hubmapconsortium.org","last_modified_user_sub":"3e7bce63-129d-33d0-8f6c-834b34cd382e","status":"Reorganized","status_history":[{"change_timestamp":1705007218869,"changed_by_email":"Anthony_Corbett@URMC.Rochester.edu","status":"New"},{"change_timestamp":1714144609250,"changed_by_email":"bhonick@andrew.cmu.edu","status":"Processing"},{"change_timestamp":1714146039858,"changed_by_email":"hubmap@hubmapconsortium.org","status":"Valid"},{"change_timestamp":1720623439765,"changed_by_email":"bhonick@andrew.cmu.edu","status":"Submitted"},{"change_timestamp":1720623461147,"changed_by_email":"bhonick@andrew.cmu.edu","status":"Processing"},{"change_timestamp":1720624992166,"changed_by_email":"hubmap@hubmapconsortium.org","status":"Valid"},{"change_timestamp":1720625782684,"changed_by_email":"bhonick@andrew.cmu.edu","status":"Submitted"},{"change_timestamp":1720625787155,"changed_by_email":"bhonick@andrew.cmu.edu","status":"Processing"},{"change_timestamp":1720625869210,"changed_by_email":"hubmap@hubmapconsortium.org","status":"Reorganized"}],"title":"LAPMAP_20211020I SNAREseq2","uuid":"4e86fff01647cc7b224a255ad6b2a27d"},"uuid":"de73b015aafc46e9c7f873457c02fea0","display_subtype":"SNARE-seq2"} at https://ingest.hubmapconsortium.org/static/js/main.9fbbeff4.js:2:1119533 at zw (https://ingest.hubmapconsortium.org/static/js/main.9fbbeff4.js:2:1119847) at Bw (https://ingest.hubmapconsortium.org/static/js/main.9fbbeff4.js:2:1119995) at https://ingest.hubmapconsortium.org/static/js/main.9fbbeff4.js:2:1199951 at Fl (https://ingest.hubmapconsortium.org/static/js/main.9fbbeff4.js:2:556679) at t.unstable_runWithPriority (https://ingest.hubmapconsortium.org/static/js/main.9fbbeff4.js:2:582301) at Go (https://ingest.hubmapconsortium.org/static/js/main.9fbbeff4.js:2:496949) at Ml (https://ingest.hubmapconsortium.org/static/js/main.9fbbeff4.js:2:556140) at https://ingest.hubmapconsortium.org/static/js/main.9fbbeff4.js:2:556051 at D (https://ingest.hubmapconsortium.org/static/js/main.9fbbeff4.js:2:581360)

**Comment by shirey** [comment]
@bhonick The fix for this is on TEST, feel free to test out there.  We'll probably release to production in the next day or two.
