### ISSUE TITLE
Cannot Add Contributors File to Collection

### ISSUE THREAD

**Issue by bhonick** [hubmapconsortium/ingest-ui#1438]
@shirey The function on collection pages to add a contributors file does not work. When I attempt to add a contributors file and press the "submit" button, the page refreshes but the file is not attached. Additionally, there appears to be a typo -- "reffer" should be "refer."

![image](https://github.com/user-attachments/assets/a70f5500-f7ea-4f19-85ca-7207fdd1231a)

**Comment by BirdMachine** [comment]
@bhonick Having some trouble replicating this locally (the file upload part). Is there a copy of the file you're using I could test with?

**Comment by bhonick** [comment]
@BirdMachine Try something like the contributors file attached. When I try to submit it, only the Affiliation field is displayed. Additionally, in testing I get an error if I try bulk adding HuBMAP IDs like these published datasets: `HBM958.BSRD.754,HBM234.VPWQ.726,HBM793.KBHR.474`: `MUI: The data grid component requires all rows to have a unique `id` property. Alternatively, you can use the `getRowId` prop to specify a custom id for each row.`

**Comment by shirey** [comment]
@bhonick The fix for this is on TEST, feel free to test out there.  We'll probably release to production in the next day or two.
