### ISSUE TITLE
Update `Collections.creators` field to `Collections.contributors`

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/ingest-ui#1448]
For both Collections and EPICollections, change the field `creators` to `contributors`, do this in conjunction with https://github.com/hubmapconsortium/entity-api/issues/723

**Comment by BirdMachine** [comment]
Should we also revert to rendering them in separate tables, or keep them visually joined as one and just mark contacts with the checkmark?

**Comment by yuanzhou** [comment]
![image](https://github.com/user-attachments/assets/8d8de556-91e6-46cf-8780-bbe7855c5192)

**Comment by BirdMachine** [comment]
Struggling to duplicate this toLowerCase thing; Is it still happening for you @yuanzhou and could you include info on how you got there / what the logs say

**Comment by yuanzhou** [comment]
@BirdMachine I think you had fixed that last week. On TEST, search for Collection, then click one of the resulting records in search table. That's how I noticed that issue. If it's working now then you must have fixed that via https://github.com/hubmapconsortium/ingest-ui/pull/1484
