### ISSUE TITLE
Create scripts to break uploaded Vanderbilt data into datasets and register with ingest system.

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/ingest-ui#149]

**Comment by cborromeo** [comment]
@shirey I am not working on this currently, but can you tell me where to find the files uploaded by Elizabeth?  I'll need to look at these files once I do start this process.

**Comment by shirey** [comment]
On Globus: https://app.globus.org/file-manager?origin_id=28bbb03c-a87d-4dd7-a661-7ea2fb6ea631&origin_path=%2FVanderbilt%20TMC%2F2020%20Release%20Data%2F

On file system: /hive/hubmap/lz/Vanderbilt\ TMC/2020\ Release\ Data/
