### ISSUE TITLE
Copy Globus Group info to pipeline derived dataset

### ISSUE THREAD

**Issue by cborromeo** [hubmapconsortium/ingest-ui#163]
When creating a derived dataset via an automated pipeline at data submission time, copy the parent dataset's group uuid and group name to the newly created derived dataset.

**Comment by cborromeo** [comment]
@shirey I am going to put this in thr atacseq_sprint branch.  Is that correct?

**Comment by shirey** [comment]
@cborromeo Yes, please.

**Comment by shirey** [comment]
To be clear about this- it only affects datasets created by pipelines at the time of data submission.  I've updated the title and description to reflect this.  We will be handling derived data that is not from a process at submission time- for this data it will be attributed to the group who submits it.

**Comment by cborromeo** [comment]
this change was pushed to the atacseq_sprint branch

**Comment by cborromeo** [comment]
this was reviewed on TEST by Joel Welling on May 15.  it was not working
