### ISSUE TITLE
Convert old DOI suffixes to new format

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/ingest-ui#172]
Old format: HBM:XYZ-1234-ABC
New format HBMXYZ.1234.ABC

Convert all old format references in Neo4j to new format.

Entire ES will need to be reindexed when done.

**Comment by cborromeo** [comment]
@shirey will you take care of the MySQL data?  We should do this when the system is down to coordinate between the two systems.  I'll write out the Cypher query here since this is not really a code change.

**Comment by cborromeo** [comment]
Here is the cypher: MATCH (e) WHERE e.display_doi CONTAINS '-' RETURN e.display_doi, replace(replace(e.display_doi,'-','.' ),':','') AS updated_display_doi

**Comment by shirey** [comment]
> @shirey will you take care of the MySQL data? We should do this when the system is down to coordinate between the two systems. I'll write out the Cypher query here since this is not really a code change.

@cborromeo yes.  Keep track of all UUIDs deleted in a txt file and I'll delete from MySQL.

**Comment by cborromeo** [comment]
Based on Bills comment above:
step 1: store existing data: MATCH (e) WHERE e.display_doi CONTAINS '-' RETURN e.display_doi AS original_display_doi, replace(replace(e.display_doi,'-','.' ),':','') AS updated_display_doi, e.uuid

step 2: store results of existing data as a spreadsheet

step 3: execute Cypher update statement

step 4: fix mysql

**Comment by cborromeo** [comment]
Here is the UPDATE statement: MATCH (e) WHERE e.display_doi CONTAINS '-' SET e.display_doi= replace(replace(e.display_doi,'-','.' ),':','') RETURN e.display_doi AS original_display_doi, replace(replace(e.display_doi,'-','.' ),':','') AS updated_display_doi, e.uuid

**Comment by cborromeo** [comment]
@shirey I queried the hm_uuids table.  There is no column for the display doi (ex: HBM:XYZ-1234-ABC).  There is only a column for DOI_SUFFIX (ex: 589RBJF235).  Therefore, do we need to make any changes to the mysql database?  Or are the Neo4j changes the only ones necessary for this change?
