### ISSUE TITLE
Replace preferred-term for donor metadata

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/ingest-ui#184]
Replace the values stored in the preferred-term fields (group level and leaf) for Sex and Race to values suitable for display in a UI.  e.g.  Sex->Male and Sex->Female

**Comment by shirey** [comment]
@computationdoc Will update the master spreadsheet, then reimport into TEST and import into PROD.

**Comment by cborromeo** [comment]
Jonathan updated the file.  The data was loaded onto STAGE.
