### ISSUE TITLE
Track data level flags/values in Neo4j and Elasticsearch

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/ingest-ui#185]
Track and store in Neo4j and include when indexing in ES the "data level" measurements defined here:

https://docs.google.com/document/d/1ozR5pAYMV8H5o5rki2RKZe5ppkVY7CCbqb34hiB8KWg/edit#heading=h.1gayxiwci33r

Based on the above document add the following fields which are read-only via the UI, i.e. a value shows up on the view and edit screens, but isn't editable.  For now these values will be set via direct database updates.  Each value should be echoed in the Elasticsearch documents using the same attribute name.  If an attribute not present or null in Neo4j no value should be present in ES.

_____

UI label name: __Donor Metadata Status__, shown on Donor edit and view screens
attribute name: donor_metadata_status, stored in Neo4j on the Metadata node attached to a donor Entity

| value in database | displayed value     |
| ----------------- | ------------------ |
| _missing_ or null | No value set           |
|              0             | No metadata           |
|              1              | Metadata provided |
|              2             | Metadata curated |
_____

UI label name: __Sample Metadata Status__, shown on Sample edit and view screens
attribute name: sample_metadata_status, stored in Neo4j on the Metadata node attached to a sample Entity

| value in database | UI display value     |
| ----------------- | ------------------ |
| _missing_ or null | No value set           |
|              0             | No metadata           |
|              1              | Metadata provided |
|              2             | Metadata curated |

_____

UI label name: __Assay Metadata Status__, shown on Dataset edit and view screens
attribute name: assay_metadata_status, stored in Neo4j on the Metadata node attached to a dataset Entity

| value in database | UI display value     |
| ----------------- | ------------------ |
| _missing_ or null | _(show nothing in UI including the label)_        |
|              0             | No metadata           |
|              1              | Metadata provided |
|              2             | Metadata curated |

_____

UI label name: __Data Metric Availability__, shown on Dataset edit and view screens
attribute name: data_metric_availability, stored in Neo4j on the Metadata node attached to a dataset Entity

| value in database | UI display value     |
| ----------------- | ------------------ |
| _missing_ or null |  _(show nothing in UI including the label)_                   |
|              0             | No quality metrics are available    |
|              1              | Quality metrics are available |

_____

UI label name: __Processing Level__, shown on Dataset edit and view screens
attribute name: data_processing_level, stored in Neo4j on the Metadata node attached to a dataset Entity

| value in database | UI display value     |
| ----------------- | ------------------ |
| _missing_ or null | _(show nothing in UI including the label)_          |
|              0             | Uploaded data. No standardized processing has been performed by the HIVE.           |
|              1              | Processing has been performed with a standard HIVE pipeline. |
|              2             | Additional processing has been performed. |

_____

UI label name: __Dataset Sign-Off Status__, shown on Dataset edit and view screens
attribute name: dataset_sign_off_status, stored in Neo4j on the Metadata node attached to a dataset Entity

| value in database | UI display value     |
| ----------------- | ------------------ |
| _missing_ or null | _(show nothing in UI including the label)_         |
|              0             | Expert has not signed off on the data  |
|              1              | Expert has signed off on the data |

**Comment by etlds** [comment]
branch: track_data_level
