### ISSUE TITLE
Fix bug in code responding to uuid-api GET calls

### ISSUE THREAD

**Issue by cborromeo** [hubmapconsortium/ingest-ui#188]
In the calls to the UUID_WEBSERVICE_URL, I am assuming the response will contain at least one item in the array.  This is true 99% of the time (otherwise it will respond with a non-200) but there might be some edge cases where that is not the case.  Change the code to check for an empty array before attempting to get the zero-th element.

**Comment by shirey** [comment]
Closing.  Fixed under a separate issue.
