### ISSUE TITLE
Support ingest from HCA?

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/ingest-ui#19]
Is it a priority to support ingesting HCA metadata?
- It might be a down-the-road goal to support collaboration between groups.
- It might also be useful in the nearer term to give us some reasonable sample data to work with.

@mruffalo had done some work to support ingesting in the earlier portal.

(Might flag as "question": I don't have privs.)

**Comment by shirey** [comment]
@mccalluc Can we close this issue, as it is part of a larger, ongoing, more detailed effort at this point?

**Comment by mccalluc** [comment]
Feel free to close. There is still a goal of supporting ingest of cross-consortium data, but I believe the plan now is to establish a mapping between metadata fields, and to avoid too much new development work on our side. Nothing more specific for now. Closing.
