### ISSUE TITLE
Manual reorg of Stanford sample ids

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/ingest-ui#193]
Reorganize the Stanford samples based on the email from Bill on June 25 at 11:44 AM EST.

Step 1:  [Daniel] Reregister (create new entries in the system) the tissue samples and attach them to the correct organ piece during the registration
  Step 1b: [Daniel] create a spreadsheet referencing associated new and old tissue samples and what dataset(s) are linked to the old tissue samples
Step 2: [Chris] Review the new spreadsheet
Step 3: [Chuck] Break the linkage from the old tissue samples both to the organ above and dataset(s) below
Step 4  [Chuck] Create linkages from the new tissue samples to the corresponding dataset(s)
Step 5  [Chuck] Remove the old  tissue samples
Step 6 [Daniel] (could be done in parallel with steps 3 – 5) Update the Sample metadata spreadsheet
Step 7 [Chris] Review everything
Step 8 [Everyone] Celebrate!

The spreadsheet is started and is here: https://docs.google.com/spreadsheets/d/11i9ENeDfFs26anOhMJ6o3W-tWIAfGCmm6Gvnm1kKeC8/edit?invite=COyRwd4D&ts=5efbcd6c#gid=1718394209

**Comment by cborromeo** [comment]
I have completed most of these changes.  The new samples have replaced the old samples in the graph (including connections).  The old samples have been deleted.  I also deleted the samples in red in the spreadsheet by Daniel Cotter.

The only  outstanding issue concerns samples STAN0004-SI- [2 through 4].  Daniel Cotter needs to review these with another researcher.
