### ISSUE TITLE
Remove unneeded Stanford Datasets

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/ingest-ui#201]
Per email from Daniel Cotter on 7/6/2020 @ 12:18 PM ET

remove the following datasets from Neo4j and the file system:
 
7ec8e67f27d0787fd6757787e4501f14
81b3a5a64dd5dc74890f87ddfc8baa91
18ee703b569c6146fe700999bd949209
b6a33fac75cc9850acedff01ca72fe57
1fb41d7f03458651a858ba500145a8aa
c32f0161a7027501dc3033b80e87cbb2
e33686d78677a975b5ceea74877052ea
a4d49e10ad885ad352a4991e13ea236a
79dc24fcfa0691addfb16710c3b8a8f9
774e6f76e3828592f6f6002ec712fb11
be9e174b51c6895d7caa7060111e8307
06e911f7cd4576b30d840b8b54a3a832
ab8796ad9230485a2a2101b174e705c2

**Comment by cborromeo** [comment]
this was done.

**Comment by computationdoc** [comment]
Confirmed no entities exist in PROD for the listed UUIDs
