### ISSUE TITLE
Remove Test dataset

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/ingest-ui#202]
Per email from Shin and Peter on 7/6/2020 at 10:04 AM ET remove the following "HuBMAP-Testing" dataset from Neo4j and /hive/ file system:
  a304f19e6b315e7254e274017897cb80

**Comment by cborromeo** [comment]
this was done.

**Comment by computationdoc** [comment]
Review/QA: Confirmed no record for this UUID in PROD
