### ISSUE TITLE
Rework Stanford Sample IDs

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/ingest-ui#203]
This is a dupe of: https://github.com/hubmapconsortium/ingest-ui/issues/193

Per email from Daniel Cotter on 7/6 at 7:37 PM ET delete several Sample records from Neo4j and disconnect datasets from old samples onto new samples, then delete the old samples too.  Track in this spreadsheet:  https://docs.google.com/spreadsheets/d/11i9ENeDfFs26anOhMJ6o3W-tWIAfGCmm6Gvnm1kKeC8/edit#gid=612370180

Reconnect datasets from old to new, then delete old after confirming that the old datasets no longer have children.
STAN0003-LI-10 (old), STAN0003-LI-2-6 (new)
STAN0003-LI-5 (old), STAN0003-LI-2-7 (new)
STAN0003-LI-6 (old), STAN0003-LI-2-8 (new)
STAN0003-LI-7 (old), STAN0003-LI-3-1 (new)
STAN0003-LI-8 (old), STAN0003-LI-1-6 (new)
STAN0003-LI-9 (old), STAN0003-LI-4-1 (new)
STAN0003-SI-5 (old), STAN0003-SI-3-6 (new)
STAN0003-SI-6 (old), STAN0003-SI-1-8 (new)
STAN0003-SI-7 (old), STAN0003-SI-2-11 (new)
STAN0003-SI-8 (old), STAN0003-SI-4-6 (new)
 
Please delete:
STAN0003-LI-1- [1 through 5]
STAN0003-LI-2- [1 through 5]
STAN0003-SI-1- [1 through 2]
STAN0003-SI-1- [3 through 7]
STAN0003-SI-2- [1 through 10]
STAN0003-SI-3- [1 through 5]
STAN0003-SI-4- [1 through 5]
STAN0004-LI- [1 through 7]
STAN0004-SI- [2 through 4]
STAN0003-LI-11
STAN0003-LI-12

**Comment by cborromeo** [comment]
I have completed most of these changes.  The new samples have replaced the old samples in the graph (including connections).  The old samples have been deleted.  I also deleted the samples in red in the spreadsheet by Daniel Cotter.

The only  outstanding issue concerns samples STAN0004-SI- [2 through 4].  Daniel Cotter needs to review these with another researcher.
