### ISSUE TITLE
Delete UCSD datasets

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/ingest-ui#204]
Per email from Blue on July 6, 2020 at 1:44 PM ET delete the following datasets from Neo4j and local file system

194b44dd3032b4f04293c74658f1b774
c0af4eb4679cb838e9d57c883d6ef921

**Comment by cborromeo** [comment]
this is done

**Comment by computationdoc** [comment]
confirmed these UUIDs not in PROD entities
