### ISSUE TITLE
Remove ERRORed, derived datasets

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/ingest-ui#205]
Per Slack message from Joel directly to Bill on 7/6/2020 at 1:59 PM ET delete the following datasets from Neo4j and the /hive/ file system

4128c624aeac2f9eed160425e5ecb70a - errored out because of a bad filename
3f4ca505a2a1dbcfcc91e191a45091df - bad CODEX due to the channel naming problem
7d997c5aedcea22210fb48913cfc0d1b - run with out-of-date metadata.tsv

**Comment by cborromeo** [comment]
this is done

**Comment by computationdoc** [comment]
Just verified each of these three UUIDs return zero records in PROD Neo4j via: MATCH (e:Entity {uuid: '<UUID>'}) return e

Consider this reviewed
