### ISSUE TITLE
Display messages w/in Globus for Not yet published and Protected Data Group use cases

### ISSUE THREAD

**Issue by pecan88** [hubmapconsortium/ingest-ui#218]
## Feature request or Bug report

__Help Desk Issue Tracker URL__: n/a (coming from Policy group discussions)

__Message__:

Would you please configure Globus to provide the following prompt based on the use cases linked below?

Info Text: [for logged in member of consortium]
“By downloading data, you affirm you will abide by provisions of DUA signed by your institutional signatory; including not reidentifying sample donors or their families and maintaining confidentiality of HuBMAP participant data”.

Info Link: to HuBMAP DUA - https://hubmapconsortium.org/wp-content/uploads/2020/06/DUA_FINAL_2020_02_03_for_Signature.pdf 

Info Text: [user within protected data accessible group]
“By downloading data, you affirm you will abide by provisions of DUA and NIH genomic data sharing policy signed by your institutional signatory; including not reidentifying any patient and maintaining confidentiality of HuBMAP participant data”

Info Link: to NIH GDS - https://osp.od.nih.gov/scientific-sharing/genomic-data-sharing/
[If possible, also to DUA, but lower priority than NIH one  - https://hubmapconsortium.org/wp-content/uploads/2020/06/DUA_FINAL_2020_02_03_for_Signature.pdf ]

There likely will be questions on whether Globus has this capability in which case please reach out to @computationdoc to clarify based on his conversations w/ Globus.

__Links to source document / discussion (not open to public):__
https://docs.google.com/document/d/1JGAPDaocjcnh5HopDVYTRsrUGLSNeEJJ5g36ZqW5loU/edit#bookmark=id.9xkti3jd8xf9
https://docs.google.com/document/d/1JGAPDaocjcnh5HopDVYTRsrUGLSNeEJJ5g36ZqW5loU/edit#bookmark=id.qkgzpwqvtwpz

**Comment by shirey** [comment]
Closing.  Jonathan and I did spend some time to get the messages that we could into Globus.  It turns out that they don't have general enough support for this so many of these messages had to be moved to portal-ui.
