### ISSUE TITLE
Reconfigure Donor/Sample screens for single protocols.io URL

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/ingest-ui#220]
Both Donors and Samples should accept only a single protocols.io DOI URL now for protocol information.  Protocol files will no longer be accepted and Samples can only have a single protocol registered for it.

On the Donor edit screen hide the fields for:
 - Protocol document
 - Open consent
Change the help text for "Case Selection Protocol" to:  "The protocol used when choosing and acquiring a donor.  This must be provided as a protocols.io DOI URL"

On the Sample edit screen hide the section for adding multiple protocols: protocols.io DOI and Protocol document fields and the "Add Protocol" button

Add a single field "Protocol" for a protocol.io DOI entry that  reads/stores the protocol entry in the Metadata.protocol field.  The "do not provide phi" icon should display for it and the help text should read:  "The protocol used when procuring or preparing the tissue.  This must be provided as a protocols.io DOI URL"

On the Sample "View" form remove the display of multiple protocols (protocols.io and/or files) and add a field to display the single entry of the Metadata.protocol field

**Comment by etlds** [comment]
branch: sample-single-protocol
