### ISSUE TITLE
Update File System Params in app.cfg

### ISSUE THREAD

**Issue by cborromeo** [hubmapconsortium/ingest-ui#239]
The changes to the Globus endpoint configuration added three filepaths:

GLOBUS_PUBLIC_ENDPOINT_FILEPATH 
GLOBUS_CONSORTIUM_ENDPOINT_FILEPATH 
GLOBUS_PROTECTED_ENDPOINT_FILEPATH 

We deploy the code via docker and it is easier to map a single path within docker instead of separate paths for each item.

To fix: 1.  create a new parameter in app.cfg called GLOBUS_ENDPOINT_BASEPATH.  this would be something like /hive/prod/parent_dir
2.  Create 3 new parameters to replace the 3 GLOBUS_*_ENDPOINT_FILEPATH entries:

GLOBUS_PUBLIC_ENDPOINT_SUBDIR 
GLOBUS_CONSORTIUM_ENDPOINT_SUBDIR 
GLOBUS_PROTECTED_ENDPOINT_SUBDIR

3.  Modify the code to resolve filepaths using GLOBUS_ENDPOINT_BASEPATH + '/' + GLOBUS_*_ENDPOINT_SUBDIR

**Comment by shirey** [comment]
Closing because a previous release changed this.
