### ISSUE TITLE
For after first data release: make ingested datasets read-only

### ISSUE THREAD

**Issue by pdblood** [hubmapconsortium/ingest-ui#262]
Feature request: once a dataset has been ingested and is in the QA state in the portal, permissions for Globus and commandline access to that dataset directory should be made read-only for all users.

**Comment by shirey** [comment]
This is the case (published datasets are read only).  I'm going to leave this here so we can double check, though.

**Comment by yuanzhou** [comment]
Can we close this issue?

**Comment by shirey** [comment]
This is now done as part of the Publication process.
