### ISSUE TITLE
Datasets to delete

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/ingest-ui#270]
Delete, then reindex datasets reverenced in the to communications:

From Joel on Slack:
@Chuck Borromeo @Bill Shirey please delete the following datasets from PROD.  They are derived datasets from outdated seqFISH datasets.

Joel Welling  6:23 PM
Untitled 
Dataset fe286895a790be94d3c2c5d2effd0c06: HBM474.DRHH.767
Dataset aed54d6ff4ea98b3953c05365133f494: HBM887.JFBN.278
Dataset e7ac61f584967eaafceee4f97402979f: HBM578.HSNW.224
Dataset 8c32bc20a324ae2f2f52388d8e0470ab: HBM454.RZLJ.863
Dataset ac7414fab0aac12d8898a52d0b482bb8: HBM385.DXBB.926
Dataset 65c8e8c290c4284b38f7015807963654: HBM824.JDKZ.654
Dataset 88a02733e475711db9c11260838e8368: HBM296.VMQB.639
Dataset 06054e34f33bf8a1cdc75515a2463d63: HBM674.MHBC.687
  and
Dataset eb8dc7f14ed3c2f46a4dfc8fb50b6896: HBM952.BWCR.777

From Phil on Slack:
The others are marked DELETE in this spreadsheet (please don't share this with others), FYI. @Bill Shirey this is something to take care of at some point. https://docs.google.com/spreadsheets/d/1J33mBUCNYRBsLN1LZMzVGWarQWjFSgbPR3ZZE3oBFjk/edit#gid=0
Column J has the DELETE note

**Comment by jswelling** [comment]
Here's another one: 
[Threaded comment from @shirey ](https://hubmapconsortium.slack.com/archives/C011RF3NQ23/p1597960235038200?thread_ts=1597953484.009500&cid=C011RF3NQ23)
