### ISSUE TITLE
Ability to submit multiple datasets into piplelines that act on them

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/ingest-ui#273]

**Comment by cborromeo** [comment]
As per discussion with @jswelling : We need to modify the /datasets/derived POST method.  This method currently assumes only one dataset is supplied via the parameter 'source_dataset_uuid'. Joel needs the ability to send an array.  I will modify the code to accept an array of items in the 'source_dataset_uuid' parameter.

**Comment by cborromeo** [comment]
I created the aptly named cborromeo/multiple_source_derived_dataset branch.  I deployed this code to DEV for @jswelling  to test.

**Comment by cborromeo** [comment]
Joel tested the code on DEV.  He has some more tests to run, but it looks good.
