### ISSUE TITLE
Remove references to rmsk.bam files in Caltech and Stanford SnapATAC datasets and reindex

### ISSUE THREAD

**Issue by pdblood** [hubmapconsortium/ingest-ui#275]
@cborromeo : Please **remove** file references to **rmsk.bam** files in the following datasets, and then **reindex** so they do not appear in the portal:

HBM626.JKSH.835: https://portal.hubmapconsortium.org/browse/dataset/d4493657cde29702c5ed73932da5317c
HBM485.TBWH.322: https://portal.hubmapconsortium.org/browse/dataset/210d118a14c8624b6bb9610a9062656e
HBM544.VKZP.647: https://portal.hubmapconsortium.org/browse/dataset/e923d09c0f0b7a0da4d53695e1b167f6

**Comment by cborromeo** [comment]
@pdblood This is done.  The data was updated in Neo4j and reindexed in ElasticSearch.  This was done on PROD.
