### ISSUE TITLE
Fix bug in UI when displaying "cherry picked" source uuids

### ISSUE THREAD

**Issue by cborromeo** [hubmapconsortium/ingest-ui#276]
We have been asked to manually connect sample ids from different samples to datasets.  For instance:

STAN0003-SI-3-6
STAN0003-SI-1-8
STAN0003-SI-2-11
STAN0003-SI-4-6

These samples don't share a common prefix (ex: STAN0003-SI-3) so our UI cannot correctly display text in the source uuid in the UI.  Instead it shows something like:

"a subset of STAN0003-SI-3-[ between 6 and 6]"

In this case, we should simply list the sample hubmap identifiers (STAN0003-SI-1-8,STAN0003-SI-2-11, STAN0003-SI-3-6,  STAN0003-SI-4-6) in alphabetical order.

**Comment by shirey** [comment]
Closing, invalid after recent updates.
