### ISSUE TITLE
Return the display_doi in the UUIDGenerator getUUID(nexus_token, sourceID) method

### ISSUE THREAD

**Issue by cborromeo** [hubmapconsortium/ingest-ui#277]
We should return the display doi in the UUIDGenerator getUUID(nexus_token, sourceID) method.  In the ingest UI, we show two types of identifiers based on the type of the source uuid.  If the source is a sample, then we show the Hubmap Identifier.  If the source is a dataset, then we show the display doi.  The current UUIDGenerator does not return the display_doi only the doiSuffix.  I need the display doi for creating the source list for the UI (or a helper method that builds the display doi)

**Comment by shirey** [comment]
Closing because this has been fixed already.
