### ISSUE TITLE
Bugfix: IndexError list index out of range encountered on some GET /datasets/uuid calls

### ISSUE THREAD

**Issue by cborromeo** [hubmapconsortium/ingest-ui#278]
Some calls to GET /datasets/<uuid> are throwing 400 Bad Request with a message " IndexError list index out of range".  This was seen on DEV with this call:

https://ingest-api.dev.hubmapconsortium.org/datasets/91a46cd9228c04e77df05536a036824b

The log file shows: 

A general error occurred:
Traceback (most recent call last):
  File "./dataset.py", line 139, in search_datasets
    write_flag = self.get_writeable_flag(token, writeable_uuid_list, record)
  File "./dataset.py", line 474, in get_writeable_flag
    for role_uuid in userinfo['hmroleids']:
KeyError: 'hmroleids'

**Comment by shirey** [comment]
Closing because the new release has refactored all of this code.
