### ISSUE TITLE
Add data modality type selection to ingest form (if not there)

### ISSUE THREAD

**Issue by pecan88** [hubmapconsortium/ingest-ui#281]
## Feature request or Bug report

__Help Desk Issue Tracker URL__: n/a

__Message__:
For the next round of data submissions, I think we should add a consistent "data modality" selection field for folks to indicate the modality represented by their assay.  For example: CODEX = MxIF; scRNAseq = Transcriptomics; Shotgun LC-MS = LC-MS.

We have a list of assays in hierarchical format on the [internal drive ](https://docs.google.com/document/d/1X4wpotexDmvPtUjIN8P5kOgqDGwk0aBLxJSXgSuNqnU/edit)which I can validate when we are ready to incorporate.

**Comment by shirey** [comment]
@pecan88 Closing because this functionality will eventually be handled by the ontology services.  Feel free to reopen if you disagree.
