### ISSUE TITLE
UI support for multiple ancestors for a dataset

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/ingest-ui#298]

**Comment by cborromeo** [comment]
We need the dataset UI to permit the user to select any combination of datasets and samples as the source for dataset.  For example the user should be able to select:

**Comment by cborromeo** [comment]
@shirey I have some questions:
- do we need to permit selecting samples from different donors?
- do we need to permit selecting from different organs (ex: TEST0001-LK-1, TEST0001-RK-1)?
- do we need to permit a combination of datasets and samples?
Some of these questions are probably related to the analysis pipeline and its capabilities

**Comment by shirey** [comment]
Done in a duplicate issue last sprint.  Closing.
