### ISSUE TITLE
Add required RESTful APIs to support public release of Donor data

### ISSUE THREAD

**Issue by pecan88** [hubmapconsortium/ingest-ui#305]
## Feature request or Bug report

__Help Desk Issue Tracker URL__: N/A (Oct 14, 2020 conversation between Ajay & Jonathan)

__Message__: 

Issue for prioritization in development backlog re: public display of donor metadata

Dependency:
1.	Intra-consortium donor data sharing

**Comment by shirey** [comment]
@pecan88 Need more info.  I'm guessing our current APIs work, but I need more specifics.

**Comment by shirey** [comment]
@pecan88 ping...

**Comment by shirey** [comment]
@pecan88 and @computationdoc I'm still confused. Peter, you responded on Slack saying this is "Donor Data" vs "Donor Metadata" related.  As far as I know we really only have "Donor Data", but we are calling it metadata even though it isn't "meta".  We currently have API access to the extracted data/"metadata" for the few simple fields, age, sex, race, bmi, etc...

If we need to provide another level of access I'll need some requirements around this.  Will this other data be PHI and only accessible by certain folks (never public?)?-- If so we definitely don't have this built.

**Comment by shirey** [comment]
Closing as a) it is 3.5 years old b) I still don't have clear specs- but also c) We are updating documentation that should help with what we currently have available.
