### ISSUE TITLE
Display / download Donor data when logged in as Consortium member

### ISSUE THREAD

**Issue by pecan88** [hubmapconsortium/ingest-ui#306]
## Feature request or Bug report

__Help Desk Issue Tracker URL__: N/A (Oct 14, 2020 conversation between Ajay & Jonathan)

__Message__:

Linked with Issue #305 

Issue for prioritization in development backlog re: intra-consortium display of donor metadata.  The near term solution to sharing donor data & metadata is to make that information available via UI and/or download for authenticated HuBMAP members (only).

This item should be prioritized and completed before #305

**Comment by shirey** [comment]
@pecan88 and @computationdoc The ability to view and download donor metadata is available from the portal Donor page.  For published/public donors it is available WITHOUT login, though-  is this okay?

**Comment by computationdoc** [comment]
the comments in this issue are not parsable at this time because of undisciplined use of the terms donor data and donor metadata herein - please clarify what this is about

**Comment by computationdoc** [comment]
I "think" this is about a future state in which there is donor data in portal, not just donor metadata as there is today. the donor metadata is public, the donor data may or may not be - there are policy and processes to consider - we are collecting donor data but not releasing it or even organizing it yet...

**Comment by shirey** [comment]
@pecan88 and @computationdoc Okay- I see, I just made a similar comment in #305 .  We'll need a separate way to store this other data and API access that does not currently exist.

**Comment by shirey** [comment]
Full Donor "metadata" is available via download on the Data Portal for both logged in (Consortium only info) and public/non-logged in users.
