### ISSUE TITLE
Key request process for API access for external users

### ISSUE THREAD

**Issue by pecan88** [hubmapconsortium/ingest-ui#308]
## Feature request or Bug report

__Help Desk Issue Tracker URL__:  URL: N/A (Oct 14, 2020 conversation between Ajay & Jonathan)

__Message__:

Backlog item for defining and implementing key request process to support external developer access to utilize HuBMAP APIs.

**Comment by shirey** [comment]
Uses who need access to non-public API's can use Globus Auth to get a token/key.  Access to public information is available with no key or token.  @computationdoc Does this sound reasonable.  Maybe I'm missing something?  @pecan88 FYI
