### ISSUE TITLE
Documentation: HuBMAP-specific Globus download scripting instructions or advice

### ISSUE THREAD

**Issue by pecan88** [hubmapconsortium/ingest-ui#309]
## Feature request or Bug report

__Help Desk Issue Tracker URL__:  N/A (Oct 14, 2020 conversation between Ajay & Jonathan)

Message:

Backlog item for writing and sharing documentation to support Globus script-based download of HuBMAP data from Globus.

**Comment by shirey** [comment]
@pecan88 Need more specifics.

**Comment by shirey** [comment]
Recently released documentation covers this.
