### ISSUE TITLE
Group mis-numbered slide with tissue block peers (GE)

### ISSUE THREAD

**Issue by pecan88** [hubmapconsortium/ingest-ui#343]
## Feature request or Bug report

__Help Desk Issue Tracker URL__: n/a (sent via email)

__Message__:
It would be helpful if we could group GE's slide 26 with slides 1-25 for one of its registered tissue blocks.  Contact Liz McDonough (elizabeth.mcdonough@ge.com) with questions not covered in the message below.

We can handle this on the backend.  I’ll need to get it into the ever backed-up schedule.  Peter, Can you put a card on the GitHub board to track?

From: "Schwenk, Melissa Dawn" <mds127@pitt.edu>
Date: Thursday, January 7, 2021 at 12:44 PM
To: "Kant, Peter M" <peterkant@pitt.edu>, "McDonough, Liz (GE Research, US)" <elizabeth.mcdonough@ge.com>, William Shirey <shirey@pitt.edu>
Cc: HuBMAP Consortium Help Desk <help@hubmapconsortium.org>
Subject: RE: HuBMAP: roll back ingest?

Hi Liz,
 
This sounds like something we might be able to do from the backend. So I’ve included Bill Shirey on this email.
 
Thanks,
Melissa 
 
From: Kant, Peter M 
Sent: Thursday, January 07, 2021 12:37 PM
To: McDonough, Liz (GE Research, US) <elizabeth.mcdonough@ge.com>
Cc: HuBMAP Consortium Help Desk <help@hubmapconsortium.org>; Schwenk, Melissa Dawn <mds127@pitt.edu>
Subject: RE: HuBMAP: roll back ingest?
 
Hi Liz,
 
I think there may be and am copying in the help desk as well as Melissa Schwenk specifically on how we may best address.  Worst case, we may be able to access from the backend to make corrections.
 
Thanks,

peter
 
From: McDonough, Liz (GE Research, US) [mailto:elizabeth.mcdonough@ge.com] 
Sent: Thursday, January 7, 2021 10:21 AM
To: Kant, Peter M <peterkant@pitt.edu>
Subject: HuBMAP: roll back ingest?
 
Hi Peter, 
 
Happy New Year!
 
Do you know if there’s a way to roll back an sample ingest entry?
 
I accidentally typed 25 instead of 26 for the number of samples, so had to enter a slide independently from our block. I would prefer if they were grouped together. Example below (I would prefer 1-26 grouped together rather than the independent entry but see no way to edit/delete). Thanks for any help.

**Comment by shirey** [comment]
Closing.  This was done a while back..
