### ISSUE TITLE
Addition of institutions 

### ISSUE THREAD

**Issue by JAH386** [hubmapconsortium/ingest-ui#353]
## Feature request or Bug report

__Help Desk Issue Tracker URL__:

__Message__:

Good afternoon,

Can you please add Wave 2 and wave 3 institutions to the list of sites permitted to submit data (and show up in the ingest interface)?

**Comment by JAH386** [comment]
[Institutions.docx](https://github.com/hubmapconsortium/ingest-ui/files/5905161/Institutions.docx)

**Comment by shirey** [comment]
@JAH386 These are the institutions who are currently in the system.  Can you get me a separate list of those that need to be added?

![image](https://user-images.githubusercontent.com/5816400/106488199-73207d80-6481-11eb-8c81-fba1fad5fba6.png)

**Comment by JAH386** [comment]
Thank you Bill, please see below for an updated list. 
[Institutions Additions.docx](https://github.com/hubmapconsortium/ingest-ui/files/5905569/Institutions.Additions.docx)

**Comment by shirey** [comment]
Duplicate.  Closing.
