### ISSUE TITLE
Sample: Hide Register Location button when creating an Organ

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/ingest-ui#372]
As currently seen on DEV:
 - When creating a new organ (Tissue Sample Type == Organ), the Register Location button should be hidden. 
 - For all other Tissue Sample Types the Register Location button should be visible.
 
 
![image](https://user-images.githubusercontent.com/5816400/108762795-8a9dd400-751e-11eb-929d-fda918e5543d.png)

**Comment by davism84** [comment]
the logic in the code only shows it when the organ type is one of the following:  

["LK", "RK", "HT", "SP", "LI"].includes(this.state.organ)

should this now be changed? @shirey

**Comment by shirey** [comment]
@davism84 That is the correct list of organs, but it should only apply to tissue who has an ancestor organ of one of those types, not the organ itself.

**Comment by shirey** [comment]
@davism84 To clarify with an example, if a new tissue sample is being registered with ancestor (Source ID) of type tissue slice (TS) and that tissue slice has an ancestor of type tissue block (TB) and the tissue block has an ancestor of type organ that is a "LI" (liver) then it should show the Register Location button.  So: for NewTissue->(TS)->(TB)->(Organ/LI)->Donor, the NewTissue should be able to have its location registered.  You probably don't have this information, though.. Do you need a new method in ingest-api to retrieve the organ information?
