### ISSUE TITLE
Sample: Can't create a new Sample registration

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/ingest-ui#374]
Currently on the DEV environment:

When registering a new Sample (shown below), the "Generate ID" button turns to a spinner, but nothing is created.  Looking at the network calls in the browser developer tools it doesn't look like any calls are made to the entity-api to create the Sample.

This was tested with a user who has multiple write-group access and a group selection box pops up after clicking "Generate ID", but after selecting a group the same behavior is seen.

![image](https://user-images.githubusercontent.com/5816400/108771052-14eb3580-7529-11eb-9090-8216246d1955.png)

**Comment by davism84** [comment]
Any error message on the console.log?

**Comment by shirey** [comment]
Yes-

![image](https://user-images.githubusercontent.com/5816400/108774582-d86e0880-752d-11eb-9721-d3ea98e59094.png)

**Comment by davism84** [comment]
I think this has been fixed and it didn't make it into the dev version.  This line of code doesn't reference organ.
