### ISSUE TITLE
Extend Ingest API to include support for tracking multiple experiments, datatypes, technologies and groups of files.

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/ingest-ui#39]
When importing uploaded data it will contain information about experiments/datatypes/technologies as well as the files which will be associated with these levels .  This information needs to be included in the provenance graph.

We need generic API support to add this information.

**Comment by cborromeo** [comment]
Joel Welling and I discussed these items.  I will send Joel a message like this: {"submission_id": "7efee1919d5ffcdf0e23e50c9393ff4e", "process": "MOCK.MICROSCOPY.IMG.ALL", "provider": "Vanderbilt TMC"}.  He will send me a reply like this: {"ingest_id": "abc123", "run_id": "run_657-xyz", "overall_file_count": "99", "top_folder_contents": "["IMS", "processed_microscopy","raw_microscopy","VAN0001-RK-1-spatial_meta.txt"]"}

**Comment by cborromeo** [comment]
I committed and tested code.  We need to convert my mocked up endpoint: http://localhost:5005/datasets/submissions/request_ingest to Joel Welling's call once it becomes available.
