### ISSUE TITLE
Dataset: Can't select "Genetic Sequences" == yes

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/ingest-ui#391]
When creating a new Dataset the "Genetic Sequences" field won't select "yes" when clicking on it, and then doesn't send this required field to the WS POST.

The state of this field should either start "blank", neither yes or no is selected or yes is selected. But it is required to make a selection (it is a required field)

@BirdMachine @davism84 FYI I updated this..I had it wrong, you can't select "yes"..

**Comment by davism84** [comment]
@BirdMachine components/ingest/dataset_edit.jsx

**Comment by BirdMachine** [comment]
Now Properly Requiring input, But on a broken/empty submission the error color highlighting only targets "Yes" In addition to the error message. No's still black, which makes it look like they must answer yes.
