### ISSUE TITLE
Make the dataset link to Globus directory more prominent and open in a new tab.

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/ingest-ui#46]

**Comment by yuanzhou** [comment]
![image2](https://user-images.githubusercontent.com/195873/69578884-5cd68200-0f9f-11ea-88c5-c9535885bbf8.png)

**Comment by yuanzhou** [comment]
I made the data repository link bold and bigger, also added an icon to indicate it's an external link that opens a new tab.

![Capture](https://user-images.githubusercontent.com/195873/69654730-46820200-1043-11ea-9099-07278988bcf7.PNG)
