### ISSUE TITLE
Add new organ types

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/ingest-ui#47]
Add the organ types:
   Trachea
    left airway (left bronchus?)
    right airway (right bronchus?)

Do these belong at the organ level?

**Comment by yuanzhou** [comment]
Where should these be added to?

**Comment by cborromeo** [comment]
@shirey I am recommending the following:

TR: Trachea
LB: Left Bronchus
RB: Right Bronchus

**Comment by yuanzhou** [comment]
Thanks @cborromeo!

**Comment by yuanzhou** [comment]
Maybe after @shirey comes back next week, we should also normalize the organ types. Currently we have:
````
  BL: "Bladder",
  BR: "Brain",
  HT: "Heart",
  LK: "Kidney (Left)",
  RK: "Kidney (Right)",
  LI: "Large Intestine",
  LB: "Left Bronchus",
  LL: "Left Lung",
  LV: "Liver",
  LY: "Lymph Node",
  RB: "Right Bronchus",
  RL: "Right Lung",
  SI: "Small Intestine",
  SP: "Spleen",
  TH: "Thymus",
  TR: "Trachea",
  UR: "Ureter",
  OT: "Other"
````

It's a mixed use of Left and Right in a few places. I also sorted the organ types by alphabetical order  but not sure if they should also be grouped.

**Comment by shirey** [comment]
@yuanzhou If it is an easy fix (no changes needed on the backend or in the database (Neo4j) go ahead and normalize.  We need to release this soon as it is holding folks up from registering tissue.

Add the new items per Chuck's suggestion:
  TR: Trachea
  LB: Left Bronchus
  RB: Right Bronchus

Also,  based on a conversation I had today with someone from Florida they need to add multiple lymph nodes soon, so remove lymph node and add the following

  LY01 - Lymph Node 01
  LY02 - Lymph Node 02
  LY03 - Lymph Node 03
  LY04 - Lymph Node 04
  LY05 - Lymph Node 05
  LY06 - Lymph Node 06
  LY07 - Lymph Node 07
  LY08 - Lymph Node 08
  LY09 - Lymph Node 09
  LY10 - Lymph Node 10
  LY11 - Lymph Node 11
  LY12 - Lymph Node 12
  LY13 - Lymph Node 13
  LY14 - Lymph Node 14
  LY15 - Lymph Node 15
  LY16 - Lymph Node 16
  LY17 - Lymph Node 17
  LY18 - Lymph Node 18
  LY19 - Lymph Node 19
  LY20 - Lymph Node 20

@cborromeo Will the four digit codes mess up the backend?

**Comment by cborromeo** [comment]
@shirey The 4 digit codes will be fine.  @yuanzhou  just add these to the same file you changed today.

**Comment by yuanzhou** [comment]
No problem!
