### ISSUE TITLE
Uploads edit screen

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/ingest-ui#471]
Create uploads edit screen per:

https://docs.google.com/document/d/18igpovQnnAthfeyFN2g9ZeipvQPiuZE5Z_7bEL21YK0/edit

and

https://github.com/hubmapconsortium/ingest-ui/blob/uploads-view/upload-states.txt

All states supported, "Validate/Save" button working, connected to API per above docs, "Create Datasets" correctly shown, but not connected to API yet.

**Comment by BirdMachine** [comment]
- [ ] a task list item
- [ ] list syntax required
- [ ] normal **formatting**, @mentions, #1234 refs
- [ ] incomplete
- [x] completed

**Comment by BirdMachine** [comment]
Partially Addressed in #523 (will check off after PR merge)

**Comment by shirey** [comment]
@BirdMachine Don't forget to change the "HuBMAP Upload ID" on these pages to display the `hubmap_id` instead of the `uuid` which is displayed now.
