### ISSUE TITLE
Add wave 1 backlog information

### ISSUE THREAD

**Issue by JAH386** [hubmapconsortium/ingest-ui#475]
Add wave 1 backlog information: .tsv files

**Comment by shirey** [comment]
@JAH386 This has been sitting for a while.  Is it still valid?  Not sure what .tsv files it is referencing.

**Comment by shirey** [comment]
@JAH386 What is this for?  Can it be closed?

**Comment by JAH386** [comment]
This was from a backlog effort a while ago. This can be closed.

-Jesse

**Comment by shirey** [comment]
Closing per JAH386
