### ISSUE TITLE
On dataset creation show "Create" and "Cancel" button, on create show id and directory 

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/ingest-ui#48]
For the "create" screen after initially using the "New Dataset" button, provide "Create" and "Cancel" buttons where "Create" saves the dataset then shows the Globus link and generated id.

**Comment by cborromeo** [comment]
chuck note: while discussing this in the planning meeting, Bill wants "Create" and "Cancel" buttons initially.  After the user comes to the screen a second time (check if the globus_directory_url_path is set) then show "Save" and "Submit"

**Comment by shirey** [comment]
@cborromeo, also while doing this remove the text "To add or modify data files go to the data repository." from the dataset edit screen when we are in create mode (vs edit) as it makes no sense to show it when there is no link.

**Comment by cborromeo** [comment]
@shirey: these changes are in the 1.5 branch.  Please review

**Comment by shirey** [comment]
@cborromeo Just reviewed this and it looks good.  The original description was a bit lacking- I"m also asking for a pop-up or other that displays the generated id and link to Globus without having to return to the search screen and view again.

**Comment by cborromeo** [comment]
@shirey  I think you mentioned that during the standup.  I forgot.  I'll move this back to in progress and fix it.
