### ISSUE TITLE
New allowable organ list for RUI activation

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/ingest-ui#481]
Coordinate with Bruce to add new organ types for the RUI.

**Comment by bherr2** [comment]
Yes! Was just getting ready to file an issue for this :-)

Below is a list of the 13 Ref Organs we have now:
* Skin
* Large Intestine
* Heart
* Kidney (Left)
* Kidney (Right)
* Spleen
* Brain
* Lungs
* Lymph Node (Left)
* Lymph Node (Right)
* Pelvis (Includes Blood and Bone Marrow)
* Thymus
* Vasculature

Link to ref organ config info:
<https://github.com/hubmapconsortium/ccf-ui/blob/main/projects/ccf-shared/src/lib/components/organ-selector/organ-selector.component.ts#L7-L34>

**Comment by bherr2** [comment]
I would also propose for whoever is doing this work to move away from the hacky string matching done currently in ruiIntegration.jsx ([link](https://github.com/hubmapconsortium/ingest-ui/blob/39dd4da0025f04e5cab43a0738d113ebee48afed/src/src/components/uuid/tissue_form_components/ruiIntegration.jsx#L62)) and just have a proper lookup table.

ie. change this: https://github.com/hubmapconsortium/ingest-ui/blob/test-release/src/src/constants.jsx#L98-L131
into:
```javascript
export const ORGAN_TYPES = {
   AO: { label: "Aorta", organ_name: "Heart" },
   LK: { label: "Kidney (Left)", organ_name: "Kidney", side: "Left" },
   ...
}
```
then in ruiIntegration you can just pull the organ_name and side properties so they match with the reference organ names exactly. Should make it much easier when more reference organs are added.

**Comment by shirey** [comment]
The current list of valid organ types should be used from: https://github.com/hubmapconsortium/search-api/blob/master/src/search-schema/data/definitions/enums/organ_types.yaml

**Comment by bherr2** [comment]
That's why I said we need a lookup. As we create more and more ref organs, we will have more not exactly one-to-one matches like this. For Lung, just link to the Lung reference organ. Lymph node, I'm not sure.. PS. Pelvis includes blood and bone marrow. 

We may need to have a larger meeting to iron this out. I CC @katyb but I'll bring out to email to coordinate.

**Comment by shirey** [comment]
@davism84, @bherr2 and I discussed this yesterday.  Ultimately the RUI is looking for an ontology reference to the organ in the form of a PURL.  Let's add the PURL for allowable RUI organs to the [organ schema file](https://github.com/hubmapconsortium/search-api/blob/test-release/src/search-schema/data/definitions/enums/organ_types.yaml) as a new attribute "ontology_id" like this:
```
LI:
  description: Large Intestine
  ontology_id: http://purl.obolibrary.org/obo/UBERON_0000059
LK:
  description: Kidney (Left)
  ontology_id: http://purl.obolibrary.org/obo/UBERON_0004538
```
The PURL references to all of the supported organs are [here](https://github.com/hubmapconsortium/ccf-ui/blob/66907f18052b2c9c86e7d6e7477ceba031b9b470/projects/ccf-shared/src/lib/components/organ-selector/organ-selector.component.ts#L7-L34).

Pass this PURL along with the organ information as attribute "ontologyId" [here](https://github.com/hubmapconsortium/ingest-ui/blob/ae0beb20dcb067e700f550819879c6b88b37dbe3/src/src/components/uuid/tissue_form_components/ruiIntegration.jsx#L90)  when initializing the RUI editor
