### ISSUE TITLE
Change PHI message/question

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/ingest-ui#50]
Change the PHI yes/no question on the dataset edit screen to the following:
Label: Gene Sequences
Question: Will this data contain any human genomic sequence data?

Add an additional warning message in a red box (like on the donor edit screen that says) "Do not upload any data containing any of the 18 identifiers specified by HIPPA." Where "18 identifiers specified by HIPPA" is linked to the list of identifiers (as it was in the previous question).

**Comment by yuanzhou** [comment]
Create new dataset:

![image1](https://user-images.githubusercontent.com/195873/69578801-36b0e200-0f9f-11ea-94f9-1c2d4c929417.png)

Edit dataset:

![image2](https://user-images.githubusercontent.com/195873/69578802-36b0e200-0f9f-11ea-9830-3019e3a79275.png)
