### ISSUE TITLE
Possible error (may have been addressed): Group selection with Donor creation

### ISSUE THREAD

**Issue by yuanzhou** [hubmapconsortium/ingest-ui#503]
When I tested with the `test-release` branch of ingest-ui locally and on TEST, I couldn't create a new Donor due to Globus group selection. I belong to HuBMAP-Data-Admin, IEC-Testing and HuBMAP-Read, but the selection popup only shows IEC-Testing and I got this error (from uuid-api) with submitting the new donor form:

````
{"error":"400 Bad Request: Lab with specified id:89a69625-99d7-11ea-9366-0e98982705c1 does not contain a tmc_prefix."}
````
I reproduced the same issue on TEST, but on DEV and STAGE with the `uber-search` stuff, it works fine.

**Comment by davism84** [comment]
@yuanzhou this selection only shows groups you are in that are data providers only.
