### ISSUE TITLE
Uploads Create: Creation dialog not modal

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/ingest-ui#507]
The Upload creation dialog is not model- i.e. if you click off to the side, on the page below it will disappear.  Please make it modal, such that the only way to dismiss it is via the "Create" or "Cancel" buttons.

**Comment by BirdMachine** [comment]
Material UI doesn't distinguish Modals by this but Does for Dialogs. No PR yet but commit in https://github.com/hubmapconsortium/ingest-ui/commit/8aaff4c472e1e190999540d02dd018764d9629b0
