### ISSUE TITLE
Dataset source lookup should include datasets

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/ingest-ui#51]

**Comment by cborromeo** [comment]
@shirey how should I organize the drop-down when looking up Dataset source id.  I need to add 'Dataset' to the list.  Here is the current list: 
![Screen Shot 2019-11-15 at 3 45 32 PM](https://user-images.githubusercontent.com/5503816/68974598-2048a080-07bf-11ea-903d-6dfb33243191.png)

**Comment by shirey** [comment]
Above the line that is above above Donor seems okay.

**Comment by cborromeo** [comment]
@shirey I pushed these changes to the 1.5 branch.

**Comment by cborromeo** [comment]
@shirey This is checked into 1.5.  Please check
