### ISSUE TITLE
Collect information on Data Set upload

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/ingest-ui#6]
When a user initiates a data upload, display a screen to collect other information before proceeding to the file upload.  Initially, just ask for a "Dataset Name", validate that it is a unique dataset name before saving and save into a new dataset db table.  After saving pass the name to the file upload section-  #13.

**Comment by BirdMachine** [comment]
Interface for Creation of Uploads has since been re-addressed in a new form
Associated Project assigned is Closed
