### ISSUE TITLE
Define TMC and Lab concepts in Neo4j

### ISSUE THREAD

**Issue by frdougal** [hubmapconsortium/ingest-ui#66]
We need to capture information for both the TMC (ex: Vanderbilt TMC, University of Florida TMC) and the Lab within the TMC.  Nils and Chuck McCallum will describe the initial design (relationships, attributes, etc.) and Chuck Borromeo will implement them in Neo4j plus any associated API changes required to store the data.

**Comment by cebriggs7135** [comment]
@cborromeo please give assignee status so I can transfer this task from nils to me. I would also like to be able to assign labels.

**Comment by cborromeo** [comment]
@cebriggs7135 please let my know if this worked.  Assigning labels might be at the repository level @shirey may need to make this change.

**Comment by cebriggs7135** [comment]
I'm not sure if I can un-assign Nils but it looks like I'm one of the 3 assignees. Is it possible to unassigned someone else?

**Comment by cborromeo** [comment]
I think so.  you just click the "gear" icon next to assignees.  Then use the checkboxes to add/remove people.

**Comment by cebriggs7135** [comment]
Define TMC & Lab organization.pdf
[Define TMC & Lab organization.pdf](https://github.com/hubmapconsortium/ingest-ui/files/4042430/Define.TMC.Lab.organization.pdf)

**Comment by cebriggs7135** [comment]
@cborromeo There are no gear icons on my screen: 
![Screen Shot 2020-01-09 at 3 54 27 PM](https://user-images.githubusercontent.com/8284878/72104016-6e2de080-32f8-11ea-9c9b-3f04e4df3b24.png)
