### ISSUE TITLE
Fix paths in Neo4j on uploaded files in UUID system

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/ingest-ui#68]

**Comment by cborromeo** [comment]
Done in production.  I ran the following code to fix the paths:

Protocols:
 
MATCH (e) WHERE e.protocols IS NOT NULL  SET e.protocols = REPLACE(e.protocols, '/home/ec2-user/temp', '/hive/hubmap/lz/tissue-reg-data')  RETURN e.uuid, e.protocols
 
Metadata:
 
MATCH (e) WHERE e.metadatas IS NOT NULL AND e.metadatas <> '[]' SET e.metadatas = REPLACE(e.metadatas, '/home/ec2-user/temp', '/hive/hubmap/lz/tissue-reg-data')  RETURN e.uuid, e.metadatas
 
Images:
MATCH (e) WHERE e.image_file_metadata IS NOT NULL AND e.image_file_metadata <> '[]' SET e.image_file_metadata = REPLACE(e.image_file_metadata, '/home/ec2-user/temp', '/hive/hubmap/lz/tissue-reg-data') RETURN e.uuid, e.image_file_metadata
