### ISSUE TITLE
RUI Integration

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/ingest-ui#69]
Store the location json in an attribute named ccf_spacial in the Sample entity in Neo4j.

**Comment by boesb** [comment]
On the UUID generation screen when the selected parent/source entity is an organ and that organ is either a left or right kidney (future versions of RUI will include heart, liver, and spleen): 

Case 1: "Generate IDs for multiple samples" checkbox is unchecked
    1.  Add a Link/Button to RUI labeled "Specify Sample Location Information".
    2.  Add help icon that should read "Provide formatted location data from the CCF Location Registration Tool for this sample."
    3.  Retrieve json generated by RUI and store in a hidden field.
    4.  Save json in an attribute named ccf_spacial when sample entity is saved to the Neo4j database.

Case 2:   "Generate IDs for multiple samples" checkbox is checked
    1.  Add a label that says "Location information can be provided on the next screen after generating the HuBMAP IDs" next to checkbox.
    2.   On the next screen, Click Assign Lab Ids. For each of the generated samples on the following screen, add a Link/Button (as in Case 1, step 1).
    3.   Repeat steps 2-4 from Case 1 for each new sample.

**Comment by boesb** [comment]
Checked in changes to  rui_integration branch.  Needs to be tested.
