### ISSUE TITLE
Create HuBMAP Display IDs for datasets

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/ingest-ui#72]
On dataset creation create a dataset display id or "HuBMAP ID" for the dataset in a similar fashion to what is created for donors and samples.  The beginning of the ID is the HuBMAP ID of the parent with a -D### added where ### is a serializer for the number of datasets attached to a give parent/source, for example two datasets attached to the 17th slice of the third block from the liver of Test Donor 3 would be TEST0003-LI-3-17-D1 and TEST0003-LI-3-17-D2

**Comment by shirey** [comment]
Create "HuBMAP Display IDs" for new (and retrospectively) datasets where the dataset identifier starts with a "D", so for example TEST0004-LI-3-5-2-D5.  Also change the UI to display this ID instead of all of the instances where the doi is displayed.

**Comment by cborromeo** [comment]
@shirey How should I handle datasets using multiple sources (ex: TEST0036-BK-1-2 through TEST0036-BK-1-6)?  Do I assign the number to the lowest sample hubmap id (TEST0036-BK-1-2)?

**Comment by cborromeo** [comment]
I will need this Cypher to initialize the data:

MATCH (e)-[:HAS_METADATA]->(m) WHERE e.entitytype = 'Dataset' SET m.next_dataset_identifier=1  RETURN e.uuid,m.next_dataset_identifier

**Comment by shirey** [comment]
@cborromeo For datasets that have multiple ancestors that are tissue samples create the base id like: TEST004-LI-3-4-var-D## if the ancestors are multiple datasets create it like this: TEST004-LI-3-4-Dvar-D###.  Where var represents "various".  Some examples:
- A dataset with ancestors including all in a range. Ancestors:TEST004-LI-3-4-[1-20]  Dataset: TEST004-LI-3-4-var-D1
- A dataset with several ancestors from a range of tissue samples, but not all samples in the range: Ancestors:TEST004-LI-3-4-7, TEST004-LI-3-4-9, TEST004-LI-3-4-11 Dataset:TEST004-LI-3-4-var-D2
- A dataset with ancestors from another range of tissue samples, all inclusive: Ancestors:TEST004-LI-3-4-[50-100] Dataset:TEST004-LI-3-4-var-D3
- A dataset with multiple ancestors that are datasets: Ancestors: TEST004-LI-3-4-D1, TEST004-LI-3-4-D2, TEST004-LI-3-4-D3 Dataset: TEST004-LI-3-4-Dvar-D1

**Comment by cborromeo** [comment]
@shirey I am just about done.  However, I can't do this part:

"A dataset with multiple ancestors that are datasets: Ancestors: TEST004-LI-3-4-D1, TEST004-LI-3-4-D2, TEST004-LI-3-4-D3 Dataset: TEST004-LI-3-4-Dvar-D1"

There is no method for selecting multiple datasets.  You can use one dataset as the source for another dataset.  However, we only allow selecting multiple items if these items were generated in a group (ex: a group of 10 biopsies).  We do not have any functionality to create a group of datasets yet.

**Comment by cborromeo** [comment]
These changes are done and were added to the 1.9_cdb_features branch

**Comment by shirey** [comment]
The changes for this are stashed in the ingest-ui repo branch feature/dataset_display_ids

**Comment by shirey** [comment]
closing.  It was decided that we won't generate this type of ID for datasets.
