### ISSUE TITLE
Change logic for when Uploads validate button is available

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/ingest-ui#748]
To give access to the validation function to Data Providers for Uploads add these additional checks for displaying the "Validate" button on the Uploads edit form:
 - In addition to current group constraints the user who is logged in can be a member of the Globus group with the same group uuid as the `group_uuid` of the Upload.
 - Additionally the "New" `status` is a valid state for the Upload to display the Validation button (in addition to other current states).

**Comment by jeffechiu** [comment]
Completed.
