### ISSUE TITLE
Recognize `alt-name`s in assay_types.yaml when displaying data types in dropdown

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/ingest-ui#752]
In addition to matching the `Dataset.data_type` code to the standard codes, when an "alt-name" from [assay_types.yaml](https://github.com/hubmapconsortium/search-api/blob/test-release/src/search-schema/data/definitions/enums/assay_types.yaml) matches this code display the associated description from the same section in the assay_types.yaml.

**Comment by jeffechiu** [comment]
Not started.

**Comment by shirey** [comment]
Instead of supporting the alt-codes in the UI we'll update the database to include only primary codes.
