### ISSUE TITLE
Incorrect group selection 

### ISSUE THREAD

**Issue by yuanzhou** [hubmapconsortium/ingest-ui#756]
Had this error on both DEV and TEST with creating a new dataset:
![image](https://user-images.githubusercontent.com/195873/148815489-5a2554d9-865b-4ccb-aba4-58e4cc41f30f.png)

I chose the IEC Testing group from popup but the ingest-ui seemed to use Data Admin Group and thus got this error. 

Note: Bill and Mike tested but it worked fine for them. Maybe just my Globus groups issue.

**Comment by BirdMachine** [comment]
Cannot reproduce, possibly fixed in #842 #840
