### ISSUE TITLE
Upload form validation

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/ingest-ui#806]
On Save/Validate button press on the Upload screen provide feedback to the user to show if a field needs to be filled.  Currently the form does nothing if either title or description are not filled- no feedback is given.  Provide feedback to the user in the same way as the other forms.  Also only `title` is required, `description` is optional.

**Comment by BirdMachine** [comment]
Fixed in #944 
Details of issue superseded by #940 & #939
