### ISSUE TITLE
Dataset Save button broken

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/ingest-ui#808]
The issue seems to be that no backend save service is being called when trying to change the value of a Data Type when the Data Type was previously displayed in the "Other" box next to the Data Type drop down.  It could be that validation is failing and no feedback is being given to the user.

From Joel on Slack in private message between Bill/Zhou/Joel:

Joel Welling 2/3/2022 11:43 AM
@Bill Shirey @Zhou (Joe) Yuan I'm hitting the submit button on https://ingest.hubmapconsortium.org/datasets/488f364142c308a9692e0b529f6697dd and nothing is happening- the button doesn't even turn into a spinner.  Is some sort of update in progress?

![image](https://user-images.githubusercontent.com/5816400/153527486-d8d1064b-25aa-4d45-99d4-1c66e0785d53.png)

**Comment by BirdMachine** [comment]
Can't Replicate, "Other" Type no longer supported
