### ISSUE TITLE
Search getting CORS errors

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/ingest-ui#812]
After randomly running a several searches in a row, selecting different Groups and Types from the dropdowns, adding keywords, blanking the keywords I'm seeing a CORS error, below is the last think I tried, when I got the error, but I'm not sure if this causes an issue directly with CURL or Postman..:

POST to `https://search-api.dev.hubmapconsortium.org/search`  with a payload of:

```
{"query":{"bool":{"must":[{"match":{"group_uuid.keyword":"07a29e4c-ed43-11e8-b56a-0e8017bdda58"}},{"match":{"specimen_type.keyword":"organ"}}]}},"from":0,"size":100,"sort":[{"last_modified_timestamp":"desc"}]}
```

**Comment by yuanzhou** [comment]
Same cause due to 10MB payload limit from AWS API Gateway: https://github.com/hubmapconsortium/aws-api-gateway/issues/3
