### ISSUE TITLE
Add new components

### ISSUE THREAD

**Issue by yuanzhou** [hubmapconsortium/ingest-ui#925]
We added 4 new components to the registration system:
- HIVE TC - University of Florida
- TMC - BIDMC
- TMC - Children's Hospital of Philadelphia Heart
- TMC - University of Rochester Medical Center

 Will also need to:
- add to TMCs ingest-ui dropdown
- create TMCs PSC file system sub directory
- add to commons groups json
- create globus groups for the TMCs
- authorize directories in Globus for TMC write access

**Comment by shirey** [comment]
Additionally add:

The following  new components have been added to the registration system:

- Demonstration Project - Lurie Children's
- TMC - GE-Pitt
- TMC - Stanford University Bone Marrow
- TMC - Washington University in St. Louis Kidney
- TMC - Johns Hopkins University

**Comment by shirey** [comment]
This is complete

The following were not added for data upload:
  - HIVE TC - University of Florida-- Tools Components don't upload data
  - TMC - Children's Hospital of Philadelphia Heart-- This replaces the current CHOP project, so we'll use the same directories/groups/etc.. for data upload/download
  - TMC - GE-Pitt - Replaces current GE project
  - TMC UCSD Pregnant Female Reproductive - Replaces current UCSD Female Reproductive project
  - Demonstration Project - Lurie Children's - Demo projects don't upload data.
