### ISSUE TITLE
Populate Data Type drop-down with primary data types

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/ingest-ui#942]
The Data Type drop-down on the Dataset edit screen is being populated with non-primary (derived/processed) data types.  This should be populated with primary only data types.

It looks like at startup/login the service call to populate these values is being called as `https://search-api.test.hubmapconsortium.org/assaytype?primary=false` when it should be `https://search-api.test.hubmapconsortium.org/assaytype?primary=true`

Also, this service call seems to be called three separate times which seems like it may be redundant.

**Comment by BirdMachine** [comment]
Is there a place where the full set of datatypes should be made available? When rendering a non-editable and post-processed entry?
The variety of redundant calls won't really be fixable without bringing the forms up to date as well, unless a lot of time is spent investigating & mitigating now-outdated class & rendering processes from two different incompatible versions of React And Router
