### ISSUE TITLE
Search: Data Upload Group Name Column empty

### ISSUE THREAD

**Issue by BirdMachine** [hubmapconsortium/ingest-ui#955]
![Screenshot from 2022-10-20 12-24-55](https://user-images.githubusercontent.com/8226070/197005238-16948e4c-d172-436e-9b69-2d7901887726.png)

Check to make sure this is displaying after the [Add group_name to indices issue](https://github.com/hubmapconsortium/search-api/issues/451) in search-api has been finished.

**Comment by BirdMachine** [comment]
Related to Search API issue https://github.com/hubmapconsortium/search-api/issues/451

**Comment by BirdMachine** [comment]
Also Duplicate of #845

**Comment by shirey** [comment]
@BirdMachine coordinate with @kburke and check this to make sure it is working once https://github.com/hubmapconsortium/search-api/issues/451  has been released to TEST.

**Comment by kburke** [comment]
Fix for [search-api#451](https://github.com/hubmapconsortium/search-api/issues/451)  verified on Dev, after Joe re-indexed Dev ElasticSearch content.
