### ISSUE TITLE
Change `Tissue Sample Type` dropdown to `Tissue Sample Category`

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/ingest-ui#970]
We do not want to collect the specific Tissue Sample Types any longer at Sample registration time.  Instead we'll collect a Tissue Sample Category that will be stored in the new `Sample.sample_category` field added by issue [Add `sample_category` field](https://github.com/hubmapconsortium/entity-api/issues/400).  This is a required field and the allowable value list is (display value: stored code):
```
  Organ: organ
  Block: block
  Section: section
  Suspension: suspension
```

 - Triggering for organ subtype will now be from this field (organ dropdown appears on Sample edit page)
 - The list of specimen/sample type in the search page switches to this category list instead
 - Need to check that the RUI enable logic isn't affected by this change

**Comment by BirdMachine** [comment]
Addressed in the Sample Categories update started in #1001
