### ISSUE TITLE
Align Source HuBMAP ID, Tissue Sample Type and Protocol help icons with others

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/ingest-ui#99]
![image](https://user-images.githubusercontent.com/5816400/74184754-55755b00-4c15-11ea-801a-8643795ced66.png)

**Comment by boesb** [comment]
Moved protocol tooltip icon outside of protocol card: protocol.jsx
Modified App.css  and added classes to protocol.jsx and tissueForm.jsx in order to move all question icons to the right.

**Comment by boesb** [comment]
Icons on view page need to be right justified.

**Comment by boesb** [comment]
Icons on view page need to be right justified.

**Comment by boesb** [comment]
Icons on both form and view pages are right justified.
