### ISSUE TITLE
data type codes are lower-cased

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/ingest-ui#995]
From Joel via Slack:
This is a potential bug report for ingest-ui .  I created a new dataset intended to be a clone of one of the Stanford TMC CODEX datasets on PROD, and selected 'CODEX' from the pull-down menu of assay types.  When I view the new dataset in the Portal, it says the assay type is 'no translation for "codex"', which I think means that the assay type got entered into the database in lowercase.  (The proper name is all uppercase).  I'm not sure where that mapping takes place, but I'm imagining that the select widget for the pulldown has a value string that is lowercase when it needs to be uppercase.

I don't know if there is a further stage of mapping, but the value of that option is in fact lower case.

The dataset in question is HBM683.TNVW.555 ecb5bed04491816bb12794eab6ff3f79 .

**Comment by BirdMachine** [comment]
Merged in PR #998
